const {test,expect}=require('@playwright/test');
require('node:fs').mkdirSync('artifacts',{recursive:true});
test('Signal Density loads, filters, interests and read state remain stable',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Portada generada');
 await expect(page.locator('#period')).toHaveValue('14');await expect(page.locator('#sort')).toHaveValue('date');
 await expect(page.locator('#coverage-title')).toHaveText('Miramos mucho para mostrarte poco.');
 await expect(page.getByRole('link',{name:'Cómo seleccionamos lo que importa →'})).toHaveAttribute('href','coverage.html');
 const coverage=await (await page.request.get('/data/product.json')).json();
 if(coverage.queue_status==='measured'){
  await expect(page.locator('#coverageCounts')).toContainText(`${new Intl.NumberFormat('es-CL').format(coverage.coverage_live.detected)} señales detectadas`);
  await expect(page.locator('#coverageCounts')).toContainText(`${Object.values(coverage.sources).filter(x=>x.technical_status==='ok'||(!x.technical_status&&['ok','warning'].includes(x.status))).length} fuentes activas`);
 }else await expect(page.locator('#coverageCounts')).toContainText('sin medición global');
 await page.locator('#period').selectOption('90');
 await expect(page.locator('article').first()).toBeVisible();
 if(test.info().project.name==='mobile'){
  const heights=await page.locator('article').evaluateAll(xs=>xs.slice(0,3).map(x=>Math.round(x.getBoundingClientRect().height)));
  expect(heights.length).toBe(3);expect(Math.max(...heights)).toBeLessThan(420);
 }
 await page.screenshot({path:`artifacts/${test.info().project.name}-browse.png`,fullPage:true});
 await page.locator('.briefitem').first().click();
 await expect(page.locator('article.read').first()).toBeVisible();
 const ids=await page.locator('article').evaluateAll(xs=>xs.map(x=>x.id));expect(new Set(ids).size).toBe(ids.length);
 await page.locator('article').first().getByRole('button',{name:/Marcar/}).click();
 expect(await page.locator('article').evaluateAll(xs=>xs.map(x=>x.id))).toEqual(ids);
 await expect(page.locator('article').first().locator('.intel,.related')).toHaveCount(0);
 const withDepth=page.locator('article:has([data-detail])').first();await withDepth.locator('[data-detail]').click();
 await expect(page.locator('#signalDetail')).toBeVisible();await page.getByRole('button',{name:'Cerrar resumen'}).click();
 await page.getByRole('link',{name:'Cómo seleccionamos lo que importa →'}).click();await expect(page.getByRole('heading',{name:'Qué significan las cifras'})).toBeVisible();await page.goBack();
 await page.getByRole('button',{name:'Personalizar mi radar'}).click();
 await expect(page.locator('#interests')).toContainText('Todo viene incluido. Desmarca lo que no quieras ver.');
 await expect(page.locator('#interestTypes input[value="Fiscalización"]')).toBeChecked();
 await page.locator('#interestTypes input[value="Fiscalización"]').uncheck();
 expect(await page.locator('article .tag').allTextContents()).not.toContain('Fiscalización');
 await page.reload();
 await page.getByRole('button',{name:'Personalizar mi radar'}).click();
 await expect(page.locator('#interestTypes input[value="Fiscalización"]')).not.toBeChecked();
 await page.locator('#interestTypes input[value="Fiscalización"]').check();
 await page.locator('#typeFilters').getByRole('button',{name:'Fiscalización',exact:true}).click();
 await expect(page.locator('article').first()).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 expect(errors).toEqual([]);
 await page.screenshot({path:`artifacts/${test.info().project.name}-radar.png`,fullPage:true});
});
test('operations dashboard loads without inventing measurements',async({page})=>{
 await page.goto('/admin/product.html');await expect(page.locator('#status')).toContainText('Actualizado:');
 await expect(page.getByRole('heading',{name:'Control de producto'})).toBeVisible();
 await expect(page.locator('#metrics')).toContainText('LIVE pending');
 await expect(page.locator('#usage')).toContainText('Costo USD: no disponible');
 await expect(page.locator('#readiness')).toContainText('No lista para Beta');
 await expect(page.locator('#requirementProgress')).toContainText('requisitos validados con evidencia');
 await expect(page.locator('#externalObservations')).toContainText('Validado técnicamente / pendiente observación externa');
 await expect(page.locator('#externalObservations')).toContainText('No bloquea los demás bloques MVP');
 await expect(page.locator('#blocks .block')).toHaveCount(10);
 await expect(page.locator('#failures')).toContainText('Autopilot distingue QA aprobado');
 await expect(page.locator('#deployments')).toContainText('Producción: último SHA comprobado');
 await expect(page.locator('thead th').filter({hasText:'Última consulta'})).toBeVisible();
 expect(await page.locator('thead th').filter({hasText:'Última consulta'}).getAttribute('scope')).toBe('col');
 await expect(page.locator('#sources tr').first()).toContainText('2026');
 await expect(page.locator('#excelValidation')).toContainText('2025-07 → 2026-07');
 await expect(page.locator('#excelValidation')).toContainText('desahucios voluntarios');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(test.info().project.use.viewport.width+1);
 const response=await page.request.get('/data/excel_diagnostics.csv');expect(response.ok()).toBeTruthy();
 await page.screenshot({path:`artifacts/${test.info().project.name}-product.png`,fullPage:true});
});
test('Cards V2 keep Bupa, sanctions and Circular 535 understandable',async({page})=>{
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Portada generada');
 await page.locator('#period').selectOption('90');
 const bupa=page.locator('article').filter({has:page.getByRole('heading',{name:/Bupa acelera inversiones/})});
 await expect(bupa).toContainText('La Dehesa');await expect(bupa).toContainText('Clínicas Huinganal');await expect(bupa).toContainText('Mindplace en San Damián.');
 await expect(bupa).not.toContainText('…');
 const pulse=page.locator('article').filter({has:page.getByRole('heading',{name:/Pulso de sanciones a Prestadores/})});
 await expect(pulse).toContainText('Clínica Los Carrera · 70 UF · cheque en garantía');
 await pulse.locator('[data-detail]').click();await expect(page.locator('#detailBody')).toContainText('Resoluciones incluidas en este pulso · 3');
 await expect(page.locator('#detailBody .sourceverify .related-item')).toHaveCount(3);
 await expect(page.locator('#detailBody')).toContainText('Clínica Redsalud Providencia · 200 UF');
 await page.getByRole('button',{name:'Cerrar resumen'}).click();
 const circular=page.locator('article').filter({has:page.getByRole('heading',{name:'Circular IF/N°535'})});
 await circular.locator('[data-detail]').click();await expect(page.locator('#detailBody')).toContainText('Circular IF/N°77');
 await page.locator('#detailBody .related').getByText('Normativa relacionada',{exact:false}).click();
 await expect(page.locator('#detailBody')).toContainText('Norma modificada');
 const ref=page.locator('#detailBody .related-item').filter({hasText:'Circular IF/N°77'});
 await expect(ref).toBeVisible();
 await expect(ref.getByText('Norma modificada',{exact:false})).toBeVisible();
 expect(await ref.locator('a').count()===1||await ref.getByText('enlace pendiente de verificación',{exact:false}).count()===1).toBeTruthy();
 await page.screenshot({path:`artifacts/${test.info().project.name}-cards-v2.png`,fullPage:true});
});
