const {test,expect}=require('@playwright/test');
require('node:fs').mkdirSync('artifacts',{recursive:true});
test('Signal Density loads, filters, interests and read state remain stable',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Última actualización:');
 await expect(page.locator('#period')).toHaveValue('14');await expect(page.locator('#sort')).toHaveValue('date');
 await expect(page.getByRole('heading',{name:'Encuentra lo que importa',exact:true})).toBeVisible();
 expect(await page.getByRole('heading',{name:'Encuentra lo que importa',exact:true}).evaluate(el=>el.getBoundingClientRect().height/parseFloat(getComputedStyle(el).lineHeight))).toBeLessThan(1.1);
 await expect(page.locator('#preferenceDetails')).not.toHaveAttribute('open','');
 await expect(page.locator('#subscriptionDetails')).not.toHaveAttribute('open','');
 await expect(page.locator('#filterDetails')).not.toHaveAttribute('open','');
 await expect(page.locator('.coverage,.toolbar,.weekly-cta,.preferences-panel')).toHaveCount(0);
 await expect(page.locator('#radarTitle')).toHaveText('Qué debes saber en 30 segundos');
 await expect(page.locator('#radarMetrics')).toHaveText(/^\d+ señales detectadas · \d+ seleccionadas · \d+ no leídas$/);
 const initialMetrics=(await page.locator('#radarMetrics').innerText()).match(/\d+/g).map(Number);
 await expect(page.locator('.radar-unit .method-link')).toHaveAttribute('href','coverage.html');
 const positions=await page.locator('#preferenceDetails,#subscriptionDetails').evaluateAll(xs=>xs.map(x=>Math.round(x.getBoundingClientRect().top)));
 expect(new Set(positions).size).toBe(1);
 await page.locator('#subscriptionDetails summary').click();
 await expect(page.locator('#homeEmail')).toBeVisible();await expect(page.locator('#homeEmail')).toBeDisabled();
 await expect(page.locator('#subscriptionDetails')).toContainText('La suscripción aún no está habilitada.');
 await page.locator('#subscriptionDetails summary').click();
 await page.locator('#filterDetails summary').click();
 await expect(page.locator('#period')).toBeVisible();await expect(page.locator('#sort')).toBeVisible();
 const selectTops=await page.locator('.select-grid label').evaluateAll(xs=>xs.map(x=>Math.round(x.getBoundingClientRect().top)));
 expect(new Set(selectTops).size).toBe(1);
 await page.locator('#period').selectOption('90');
 const extendedMetrics=(await page.locator('#radarMetrics').innerText()).match(/\d+/g).map(Number);
 expect(extendedMetrics[0]).toBeGreaterThanOrEqual(initialMetrics[0]);
 await expect(page.locator('article').first()).toBeVisible();
 if(test.info().project.name==='mobile'){
  const cards=await page.locator('article').evaluateAll(xs=>xs.slice(0,3).map(x=>({height:Math.round(x.getBoundingClientRect().height),title:x.querySelector('h2')?.textContent||''})));
  expect(cards.length).toBe(3);expect(Math.max(...cards.map(x=>x.height)),JSON.stringify(cards)).toBeLessThan(420);
 }
 await page.screenshot({path:`artifacts/${test.info().project.name}-browse.png`,fullPage:true});
 await page.locator('.briefitem').first().click();
 await expect(page.locator('article.read').first()).toBeVisible();
 expect(await page.evaluate(()=>document.activeElement?.tagName)).toBe('ARTICLE');
 await expect(page.locator('article.read').first().getByRole('button',{name:'Volver arriba'})).toBeVisible();
 await page.locator('article.read').first().getByRole('button',{name:'Volver arriba'}).click();
 expect(await page.evaluate(()=>document.activeElement?.tagName)).toBe('MAIN');
 const ids=await page.locator('article').evaluateAll(xs=>xs.map(x=>x.id));expect(new Set(ids).size).toBe(ids.length);
 await page.locator('article').first().getByRole('button',{name:/Marcar/}).click();
 expect(await page.locator('article').evaluateAll(xs=>xs.map(x=>x.id))).toEqual(ids);
 await expect(page.locator('article').first().locator('.intel,.related')).toHaveCount(0);
 const withDepth=page.locator('article:has([data-detail])').first();await withDepth.locator('[data-detail]').click();
 await expect(page.locator('#signalDetail')).toBeVisible();await page.getByRole('button',{name:'Cerrar resumen'}).click();
 await page.getByRole('link',{name:'Metodología'}).click();await expect(page.getByRole('heading',{name:'Qué significan las cifras'})).toBeVisible();await page.goBack();
 await page.locator('#preferenceDetails summary').click();
 await expect(page.locator('#preferenceDetails')).toContainText('Guardaremos tus preferencias en este dispositivo para tu próximo ingreso.');
 await expect(page.locator('#interestTypes input[value="Fiscalización"]')).toBeChecked();
 await page.locator('#interestTypes input[value="Fiscalización"]').uncheck();
 expect(await page.locator('article .tag').allTextContents()).not.toContain('Fiscalización');
 await page.reload();
 await page.locator('#preferenceDetails summary').click();
 await expect(page.locator('#interestTypes input[value="Fiscalización"]')).not.toBeChecked();
 await page.locator('#interestTypes input[value="Fiscalización"]').check();
 await page.locator('#filterDetails summary').click();
 await page.locator('#typeFilters').getByRole('button',{name:'Fiscalización',exact:true}).click();
 await expect(page.locator('article').first()).toBeVisible();
 const filteredMetrics=(await page.locator('#radarMetrics').innerText()).match(/\d+/g).map(Number);
 expect(filteredMetrics[1]).toBe(await page.locator('article').count());
 expect(filteredMetrics[2]).toBe(await page.locator('article:not(.read)').count());
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 expect(errors).toEqual([]);
 await page.screenshot({path:`artifacts/${test.info().project.name}-radar.png`,fullPage:true});
});
test('Inbox shows every unread signal, supports direct read and persists it',async({page})=>{
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Última actualización:');
 const initial=await page.locator('.briefitem').count();
 const expected=await page.locator('article:not(.read)').count();
 expect(initial).toBe(expected);expect(initial).toBeGreaterThan(4);
 const first=await page.locator('.briefitem').first().getAttribute('data-brief');
 await page.locator('[data-brief-read]').first().click();
 expect(await page.evaluate(()=>document.activeElement?.hasAttribute('data-brief-read'))).toBeTruthy();
 await expect(page.locator('.briefitem')).toHaveCount(initial-1);
 await expect(page.locator(`article[data-card="${first}"]`)).toHaveClass(/read/);
 await page.reload();await expect(page.locator('#meta')).toContainText('Última actualización:');
 await expect(page.locator('.briefitem')).toHaveCount(initial-1);
 await expect(page.locator(`article[data-card="${first}"]`)).toHaveClass(/read/);
 await page.locator('#filterDetails summary').click();
 await page.locator('#period').selectOption('90');
 const inbox=page.locator('.brief-list');
 const deepCount=await page.locator('[data-brief-read]').count();
 expect(deepCount).toBeGreaterThan(4);
 await inbox.evaluate(el=>el.scrollTop=el.scrollHeight);
 expect(await inbox.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
 await page.locator('[data-brief-read]').last().click();
 expect(await inbox.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
 expect(await page.evaluate(()=>document.activeElement?.hasAttribute('data-brief-read'))).toBeTruthy();
});
test('operations dashboard loads without inventing measurements',async({page})=>{
 await page.goto('/admin/product.html');await expect(page.locator('#status')).toContainText('Actualizado:');
 await expect(page.getByRole('heading',{name:'Control de producto'})).toBeVisible();
 await expect(page.locator('#metrics')).toContainText('LIVE pending');
 await expect(page.locator('#usage')).toContainText('Costo USD: no disponible');
 await expect(page.locator('#featureUsage tr')).toHaveCount(12);
 await expect(page.locator('#featureUsage')).toContainText('Global Intelligence');
 await expect(page.locator('#featureUsage')).toContainText('Insight Alicanto de la semana');
 await expect(page.locator('#featureUsage')).toContainText('No disponible');
 await expect(page.locator('#featureUsage')).toContainText('Total acumulado');
 await expect(page.locator('#featureSummary')).toContainText('output determinístico trazable');
 await expect(page.locator('#featureSummary')).toContainText('costo/output No disponible');
 await expect(page.locator('#readiness')).toContainText('No lista para Beta');
 await expect(page.locator('#requirementProgress')).toContainText('requisitos validados con evidencia');
 await expect(page.locator('#externalObservations')).toContainText('Validado técnicamente / pendiente observación externa');
 await expect(page.locator('#externalObservations')).toContainText('No bloquea los demás bloques MVP');
 const report=await (await page.request.get('/data/product.json')).json();
 await expect(page.locator('#blocks .block')).toHaveCount(report.pmo.blocks.length);
 await expect(page.locator('#failures')).toContainText('Autopilot distingue QA aprobado');
 await expect(page.locator('#deployments')).toContainText('Producción: último SHA comprobado');
 await expect(page.locator('thead th').filter({hasText:'Última consulta'})).toBeVisible();
 expect(await page.locator('thead th').filter({hasText:'Última consulta'}).getAttribute('scope')).toBe('col');
 await expect(page.locator('#sources tr').first()).toContainText('2026');
 await expect(page.locator('#excelValidation')).toContainText('2025-07 → 2026-07');
 await expect(page.locator('#excelValidation')).toContainText('desahucios voluntarios');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(test.info().project.use.viewport.width+1);
 const response=await page.request.get('/data/excel_diagnostics.csv');expect(response.ok()).toBeTruthy();
 await page.screenshot({path:`artifacts/${test.info().project.name}-product.png`,fullPage:true});
});
test('FREE value shows one verified weekly insight and a bounded Global teaser',async({page})=>{
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Última actualización:');
 const weekly=page.locator('.weekly-insight'),teaser=page.locator('.global-teaser');
 await expect(weekly).toContainText('Insight Alicanto de la semana · FREE');
 await expect(weekly).toContainText('fuente verificada');
 await expect(weekly.getByRole('link',{name:/Revisar fuente original/})).toHaveAttribute('href',/^https:\/\//);
 await expect(teaser).toContainText('Una mirada Global Intelligence · FREE');
 await expect(teaser).toContainText('Vista acotada');
 await expect(teaser.getByRole('link',{name:/Profundizar en PREMIUM/})).toHaveAttribute('href',/^global\.html#theme-/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 await page.screenshot({path:`artifacts/${test.info().project.name}-free-value.png`,fullPage:true});
});
test('source suggestion is visible, anonymous and fail-closed without provider',async({page})=>{
 let captured;
 await page.route('**/api/source-suggestions',async route=>{
  captured=route.request().postDataJSON();
  await route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({id:`src_${'a'.repeat(32)}`,status:'received',message:'Gracias. Guardamos tu sugerencia para revisión.'})});
 });
 await page.goto('/');
 const cta=page.locator('#source-suggestion');
 await expect(cta).toBeVisible();
 expect(await cta.evaluate(el=>el.getBoundingClientRect().top)).toBeLessThan(test.info().project.use.viewport.height);
 await expect(cta).toContainText('¿Nos falta alguna fuente?');
 const open=page.getByRole('button',{name:'Sugerir una fuente'});
 await open.focus();
 expect(await open.evaluate(el=>getComputedStyle(el).outlineStyle)).toBe('solid');
 await open.click();
 const dialog=page.locator('#sourceSuggestionDialog');
 await expect(dialog).toBeVisible();
 await expect(dialog.locator('input[type="email"],input[name="name"],input[name="user_id"]')).toHaveCount(0);
 await dialog.locator('[name="source_name"]').fill('Observatorio de Salud');
 await dialog.locator('[name="source_url"]').fill('https://example.org/publicaciones');
 await dialog.locator('[name="comment"]').fill('Revisar los informes trimestrales.');
 await dialog.getByRole('button',{name:'Enviar sugerencia'}).click();
 await expect(dialog.locator('#sourceSuggestionFeedback')).toContainText('Guardamos tu sugerencia para revisión');
 expect(Object.keys(captured).sort()).toEqual(['comment','source_name','source_url','started_at','website']);
 expect(captured.website).toBe('');

 await page.unroute('**/api/source-suggestions');
 await page.route('**/api/source-suggestions',route=>route.fulfill({status:200,contentType:'application/json',body:'{}'}));
 await dialog.locator('[name="source_name"]').fill('Otra fuente');
 await dialog.getByRole('button',{name:'Enviar sugerencia'}).click();
 await expect(dialog.locator('#sourceSuggestionFeedback')).toContainText('El envío aún no está habilitado. No guardamos tu sugerencia.');
 await page.unroute('**/api/source-suggestions');
 await page.route('**/api/source-suggestions',route=>route.fulfill({status:204,body:''}));
 await dialog.getByRole('button',{name:'Enviar sugerencia'}).click();
 await expect(dialog.locator('#sourceSuggestionFeedback')).toContainText('El envío aún no está habilitado. No guardamos tu sugerencia.');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 await page.screenshot({path:`artifacts/${test.info().project.name}-source-suggestion.png`,fullPage:true});
});
test('source suggestion never falls back to URL serialization without JavaScript',async({browser})=>{
 const context=await browser.newContext({javaScriptEnabled:false});
 const page=await context.newPage();
 await page.goto('/');
 const form=page.locator('#sourceSuggestionForm');
 await expect(form).toHaveAttribute('method','post');
 await expect(form).toHaveAttribute('action','/api/source-suggestions');
 await expect(form.locator('button[type="submit"]')).toBeDisabled();
 expect(await page.content()).toContain('El envío requiere JavaScript y todavía no está habilitado en este navegador. No se enviaron datos.');
 expect(page.url()).not.toContain('source_name=');
 await context.close();
});
test('Cards V2 keep Bupa, sanctions and Circular 535 understandable',async({page})=>{
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Última actualización:');
 await page.locator('#filterDetails summary').click();
 await page.locator('#period').selectOption('90');
 const bupa=page.locator('article').filter({has:page.getByRole('heading',{name:/Bupa acelera inversiones/})});
 await expect(bupa).toContainText('La Dehesa');await expect(bupa).toContainText('Clínicas Huinganal');await expect(bupa).toContainText('Mindplace en San Damián.');
 await expect(bupa).not.toContainText('…');
 await expect(bupa.locator('.card-meta')).toContainText('Publicado');
 await expect(bupa.locator('.card-meta')).not.toBeEmpty();
 await bupa.locator('[data-detail]').click();
 await expect(page.locator('#detailBody')).toContainText('Enriquecimiento editorial · 3');
 await expect(page.locator('#detailBody')).toContainText('Mismo emisor · no es corroboración independiente');
 await expect(page.locator('#detailBody')).toContainText('Conexiones históricas');
 await expect(page.locator('#detailBody')).toContainText('Expansión previa de la red ambulatoria IntegraMédica');
 await expect(page.locator('#detailBody')).toContainText('Contexto histórico: Conexión histórica disponible y atribuida al mismo artículo DF.');
 await page.getByRole('button',{name:'Cerrar resumen'}).click();
 const isapre=page.locator('article').filter({has:page.getByRole('heading',{name:/Pulso Isapre · datos/})});
 await expect(isapre.locator('.card-meta')).toContainText('Datos a 2026-07');
 await expect(isapre.locator('.card-meta')).toContainText('Publicado 07 sept 2026');
 await expect(isapre.locator('.card-meta')).toContainText('Validado 24 sept 2026');
 await isapre.locator('[data-detail]').click();
 await expect(page.locator('#detailBody .intel').filter({hasText:'Muestra de datos validada'}).locator('li')).toHaveCount(5);
 await expect(page.locator('#detailBody')).toContainText('2026-06 → 2026-07');
 await expect(page.locator('#detailBody')).toContainText('cotizantes');
 await expect(page.locator('#detailBody')).toContainText('brecha acumulada');
 await expect(page.locator('#detailBody')).toContainText('No es variación mensual');
 await expect(page.locator('#detailBody .intel a').first()).toHaveAttribute('href',/superdesalud\.gob\.cl/);
 await expect(page.locator('#detailBody .sourceverify .related-item')).toHaveCount(3);
 await expect(page.locator('#detailBody .sourceverify')).toContainText('Publicado 07 sept 2026');
 await expect(page.locator('#detailBody')).toContainText('Período de datos: 2026-07');
 await expect(page.locator('#detailBody')).toContainText('Fecha de publicación: 07 sept 2026');
 await expect(page.locator('#detailBody')).toContainText('Validado: 24 sept 2026');
 await page.getByRole('button',{name:'Cerrar resumen'}).click();
 const pulse=page.locator('article').filter({has:page.getByRole('heading',{name:/Pulso de sanciones a Prestadores/})});
 await expect(pulse).toContainText('Clínica Los Carrera · 70 UF · cheque en garantía');
 await pulse.locator('[data-detail]').click();await expect(page.locator('#detailBody')).toContainText('Resoluciones incluidas en este pulso · 3');
 const sourceBeforeDetails=await page.locator('#detailBody').evaluate(el=>el.querySelector('.sourceverify').compareDocumentPosition(el.querySelector('.intel'))&Node.DOCUMENT_POSITION_FOLLOWING);
 expect(sourceBeforeDetails).toBeTruthy();
 await expect(page.locator('#detailBody .sourceverify .related-item')).toHaveCount(3);
 await expect(page.locator('#detailBody')).toContainText('Clínica Redsalud Providencia · 200 UF');
 await page.getByRole('button',{name:'Cerrar resumen'}).click();
 const circular=page.locator('article').filter({has:page.getByRole('heading',{name:'Circular IF/N°535'})});
 await circular.locator('[data-detail]').click();await expect(page.locator('#detailBody')).toContainText('Circular IF/N°77');
 await page.locator('#detailBody .related').getByText('Normativa relacionada',{exact:false}).click();
 await expect(page.locator('#detailBody')).toContainText('Norma modificada');
 const ref=page.locator('#detailBody .related-item').filter({hasText:'Circular IF/N°77'});
 await expect(ref).toBeVisible();
 await expect(ref.getByText('Norma modificada',{exact:false})).toBeVisible();
 expect(await ref.locator('a').count()===1||await ref.getByText('enlace pendiente de verificación',{exact:false}).count()===1).toBeTruthy();
 await page.screenshot({path:`artifacts/${test.info().project.name}-cards-v2.png`,fullPage:true});
});
test('Global Intelligence keeps global facts, Chile hypotheses and PREMIUM distinct',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('link',{name:/Global Intelligence PREMIUM/})).toBeVisible();
 await page.getByRole('link',{name:/Global Intelligence PREMIUM/}).click();
 await expect(page.getByRole('heading',{name:'Global Intelligence',exact:true})).toBeVisible();
 await expect(page.locator('.premium-badge')).toHaveText('Acceso PREMIUM');
 await expect(page.getByText('Vista pública de la experiencia.',{exact:false})).toHaveCount(0);
 await expect(page.locator('.global-inbox')).toContainText('3 temas no leídos');
 await expect(page.locator('.theme')).toHaveCount(3);
 await expect(page.locator('.theme').first()).toContainText('Global Theme · research internacional');
 await page.locator('[data-open]').first().click();
 await expect(page.locator('.global-inbox')).toContainText('2 temas no leídos');
 const opened=page.locator('.theme').filter({has:page.locator('details[open]')});
 await expect(opened).toContainText('Qué mirar en Chile · hipótesis, no evidencia local');
 await expect(opened).toContainText('Lectura cruzada');
 await expect(opened).toContainText('Resumen ejecutivo');
 await expect(opened).toContainText('Hallazgos clave');
 await expect(opened).toContainText('Metodología y alcance');
 await expect(opened).toContainText('Trend Chile: no establecido');
 await expect(opened).toContainText('señales locales compatibles verificadas: 0');
 await expect(opened.getByRole('button',{name:'Volver a Global Intelligence'})).toBeVisible();
 await opened.getByRole('button',{name:'Marcar no leído'}).click();
 await expect(opened.locator('details')).toHaveAttribute('open','');
 await expect(opened.getByRole('button',{name:'Marcar como leído'})).toBeFocused();
 await opened.getByRole('button',{name:'Marcar como leído'}).click();
 await expect(opened.locator('details')).toHaveAttribute('open','');
 await expect(opened.getByRole('button',{name:'Marcar no leído'})).toBeFocused();
 await opened.getByRole('button',{name:'Volver a Global Intelligence'}).click();
 await expect(page.locator('#globalInbox')).toBeFocused();
 await page.reload();
 await expect(page.locator('.global-inbox')).toContainText('2 temas no leídos');
 await page.locator('.theme').first().getByRole('button',{name:'Marcar no leído'}).click();
 await expect(page.locator('.global-inbox')).toContainText('3 temas no leídos');
 await page.locator('[data-inbox-read]').first().click();
 await expect(page.locator('[data-inbox-read]').first()).toBeFocused();
 await expect(page.locator('.global-inbox')).toContainText('2 temas no leídos');
 await expect(page.locator('.source a')).toHaveCount(5);
 await expect(page.locator('.source a').filter({hasText:'PwC'})).toHaveAttribute('href',/^https:\/\/www\.pwc\.com\//);
 await expect(page.locator('.source a[href="https://www.who.int/publications/i/item/9789240122925"]')).toContainText(/^WHO ·/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(test.info().project.use.viewport.width+1);
 await page.screenshot({path:`artifacts/${test.info().project.name}-global-intelligence.png`,fullPage:true});
});
test('Weekly email capture requires consent and stays closed without approved provider',async({page})=>{
 await page.goto('/');
 await page.locator('#subscriptionDetails summary').click();
 await page.getByRole('link',{name:'Ver condiciones de suscripción →'}).click();
 await expect(page.getByRole('heading',{name:'Recibe lo importante, una vez por semana.'})).toBeVisible();
 await expect(page.locator('#email')).toBeDisabled();
 await expect(page.locator('#consent')).toBeDisabled();
 await expect(page.getByRole('button',{name:'Suscribirme'})).toBeDisabled();
 await expect(page.locator('#status')).toContainText('espera proveedor e información de privacidad aprobados');
 await expect(page.getByText('Si no hay material suficiente, no enviamos correo.')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(test.info().project.use.viewport.width+1);
 await page.screenshot({path:`artifacts/${test.info().project.name}-subscription.png`,fullPage:true});
});
test('analytics never sends without explicit privacy approval even if a key is present',async({page})=>{
 let attempts=0;
 await page.route('**/data/analytics.json',route=>route.fulfill({status:200,contentType:'application/json',
   body:JSON.stringify({enabled:true,privacy_approved:false,provider:'posthog',
     project_key:'public-test-key',host:'https://us.i.posthog.com'})}));
 await page.route('https://us.i.posthog.com/**',route=>{attempts++;return route.abort()});
 await page.goto('/');
 await page.locator('#preferenceDetails summary').click();
 await page.locator('#filterDetails summary').click();
 await page.locator('#period').selectOption('7');
 await expect(page.locator('#radarMetrics')).toHaveText(/^\d+ señales detectadas · \d+ seleccionadas · \d+ no leídas$/);
 expect(attempts).toBe(0);
});
test('authorized analytics fixture emits only anonymous event fields',async({page})=>{
 const payloads=[];
 await page.route('**/data/analytics.json',route=>route.fulfill({status:200,contentType:'application/json',
   body:JSON.stringify({enabled:true,privacy_approved:true,provider:'posthog',
     project_key:'public-test-key',host:'https://us.i.posthog.com'})}));
 await page.route('https://us.i.posthog.com/capture/',route=>{
   payloads.push(JSON.parse(route.request().postData()));
   return route.fulfill({status:200,body:'{}'});
 });
 await page.goto('/');
 await page.locator('#preferenceDetails summary').click();
 await expect.poll(()=>payloads.some(p=>p.event==='preferences_open')).toBe(true);
 expect(payloads.some(p=>p.event==='visit'&&typeof p.properties.returning==='boolean')).toBe(true);
 expect(new Set(payloads.map(p=>p.distinct_id)).size).toBe(payloads.length);
 for(const payload of payloads){
   expect(payload.api_key).toBe('public-test-key');
   expect(Object.keys(payload).sort()).toEqual(['api_key','distinct_id','event','properties']);
   expect(Object.keys(payload.properties).every(key=>['returning','$geoip_disable','$process_person_profile','dimension','hidden'].includes(key))).toBe(true);
   expect(JSON.stringify(payload)).not.toMatch(/source_url|email|title|https:\/\/cftorre1/);
 }
});
