const {test,expect}=require('@playwright/test');
require('node:fs').mkdirSync('artifacts',{recursive:true});
test('Signal Density loads, filters, interests and read state remain stable',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Portada generada');
 await expect(page.locator('#period')).toHaveValue('14');await expect(page.locator('#sort')).toHaveValue('date');
 await expect(page.locator('#coverage-title')).toHaveText('Miramos mucho para mostrarte poco.');
 const order=await page.locator('main > .coverage,main > .toolbar,main > #brief,main > #local').evaluateAll(xs=>xs.map(x=>x.id||x.classList[0]));
 expect(order).toEqual(['coverage','toolbar','brief','local']);
 await expect(page.getByRole('link',{name:'Cómo seleccionamos lo que importa →'})).toHaveAttribute('href','coverage.html');
 const coverage=await (await page.request.get('/data/product.json')).json();
 if(coverage.queue_status==='measured'){
  await expect(page.locator('#coverageCounts')).toContainText(`${new Intl.NumberFormat('es-CL').format(coverage.coverage_live.detected)} señales detectadas`);
  await expect(page.locator('#coverageCounts')).toContainText(`${Object.values(coverage.sources).filter(x=>x.technical_status==='ok'||(!x.technical_status&&['ok','warning'].includes(x.status))).length} fuentes activas`);
 }else await expect(page.locator('#coverageCounts')).toContainText('sin medición global');
 await page.locator('#period').selectOption('90');
 await expect(page.locator('article').first()).toBeVisible();
 if(test.info().project.name==='mobile'){
  const heights=await page.locator('article').evaluateAll(xs=>xs.slice(0,3).map(x=>Math.round(x.getBoundingClientRect().height)));
  expect(heights.length).toBe(3);expect(Math.max(...heights)).toBeLessThan(420);
 }
 await page.screenshot({path:`artifacts/${test.info().project.name}-browse.png`,fullPage:true});
 await page.locator('.briefitem').first().click();
 await expect(page.locator('article.read').first()).toBeVisible();
 expect(await page.evaluate(()=>document.activeElement?.tagName)).toBe('ARTICLE');
 await expect(page.locator('article.read').first().getByRole('button',{name:'Volver a 30 segundos'})).toBeVisible();
 await page.locator('article.read').first().getByRole('button',{name:'Volver a 30 segundos'}).click();
 expect(await page.evaluate(()=>document.activeElement?.id)).toBe('brief');
 const ids=await page.locator('article').evaluateAll(xs=>xs.map(x=>x.id));expect(new Set(ids).size).toBe(ids.length);
 await page.locator('article').first().getByRole('button',{name:/Marcar/}).click();
 expect(await page.locator('article').evaluateAll(xs=>xs.map(x=>x.id))).toEqual(ids);
 await expect(page.locator('article').first().locator('.intel,.related')).toHaveCount(0);
 const withDepth=page.locator('article:has([data-detail])').first();await withDepth.locator('[data-detail]').click();
 await expect(page.locator('#signalDetail')).toBeVisible();await page.getByRole('button',{name:'Cerrar resumen'}).click();
 await page.getByRole('link',{name:'Cómo seleccionamos lo que importa →'}).click();await expect(page.getByRole('heading',{name:'Qué significan las cifras'})).toBeVisible();await page.goBack();
 await page.getByRole('button',{name:'Personalizar mi radar'}).click();
 await expect(page.locator('#interests')).toContainText('Todo viene incluido. Desmarca lo que no quieras ver.');
 await expect(page.locator('#interestTypes input[value="Fiscalización"]')).toBeChecked();
 await page.locator('#interestTypes input[value="Fiscalización"]').uncheck();
 expect(await page.locator('article .tag').allTextContents()).not.toContain('Fiscalización');
 await page.reload();
 await page.getByRole('button',{name:'Personalizar mi radar'}).click();
 await expect(page.locator('#interestTypes input[value="Fiscalización"]')).not.toBeChecked();
 await page.locator('#interestTypes input[value="Fiscalización"]').check();
 await page.getByText('Filtrar tipo y ámbito').click();
 await page.locator('#typeFilters').getByRole('button',{name:'Fiscalización',exact:true}).click();
 await expect(page.locator('article').first()).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 expect(errors).toEqual([]);
 await page.screenshot({path:`artifacts/${test.info().project.name}-radar.png`,fullPage:true});
});
test('Inbox shows every unread signal, supports direct read and persists it',async({page})=>{
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Portada generada');
 const initial=await page.locator('.briefitem').count();
 const expected=await page.locator('article:not(.read)').count();
 expect(initial).toBe(expected);expect(initial).toBeGreaterThan(4);
 const first=await page.locator('.briefitem').first().getAttribute('data-brief');
 await page.locator('[data-brief-read]').first().click();
 expect(await page.evaluate(()=>document.activeElement?.hasAttribute('data-brief-read'))).toBeTruthy();
 await expect(page.locator('.briefitem')).toHaveCount(initial-1);
 await expect(page.locator(`article[data-card="${first}"]`)).toHaveClass(/read/);
 await page.reload();await expect(page.locator('#meta')).toContainText('Portada generada');
 await expect(page.locator('.briefitem')).toHaveCount(initial-1);
 await expect(page.locator(`article[data-card="${first}"]`)).toHaveClass(/read/);
 await page.locator('#period').selectOption('90');
 const inbox=page.locator('.brief-list');
 const deepCount=await page.locator('[data-brief-read]').count();
 expect(deepCount).toBeGreaterThan(4);
 await inbox.evaluate(el=>el.scrollTop=el.scrollHeight);
 expect(await inbox.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
 await page.locator('[data-brief-read]').last().click();
 expect(await inbox.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
 expect(await page.evaluate(()=>document.activeElement?.hasAttribute('data-brief-read'))).toBeTruthy();
});
test('operations dashboard loads without inventing measurements',async({page})=>{
 await page.goto('/admin/product.html');await expect(page.locator('#status')).toContainText('Actualizado:');
 await expect(page.getByRole('heading',{name:'Control de producto'})).toBeVisible();
 await expect(page.locator('#metrics')).toContainText('LIVE pending');
 await expect(page.locator('#usage')).toContainText('Costo USD: no disponible');
 await expect(page.locator('#readiness')).toContainText('No lista para Beta');
 await expect(page.locator('#requirementProgress')).toContainText('requisitos validados con evidencia');
 await expect(page.locator('#externalObservations')).toContainText('Validado técnicamente / pendiente observación externa');
 await expect(page.locator('#externalObservations')).toContainText('No bloquea los demás bloques MVP');
 await expect(page.locator('#blocks .block')).toHaveCount(10);
 await expect(page.locator('#failures')).toContainText('Autopilot distingue QA aprobado');
 await expect(page.locator('#deployments')).toContainText('Producción: último SHA comprobado');
 await expect(page.locator('thead th').filter({hasText:'Última consulta'})).toBeVisible();
 expect(await page.locator('thead th').filter({hasText:'Última consulta'}).getAttribute('scope')).toBe('col');
 await expect(page.locator('#sources tr').first()).toContainText('2026');
 await expect(page.locator('#excelValidation')).toContainText('2025-07 → 2026-07');
 await expect(page.locator('#excelValidation')).toContainText('desahucios voluntarios');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(test.info().project.use.viewport.width+1);
 const response=await page.request.get('/data/excel_diagnostics.csv');expect(response.ok()).toBeTruthy();
 await page.screenshot({path:`artifacts/${test.info().project.name}-product.png`,fullPage:true});
});
test('Cards V2 keep Bupa, sanctions and Circular 535 understandable',async({page})=>{
 await page.goto('/');await expect(page.locator('#meta')).toContainText('Portada generada');
 await page.locator('#period').selectOption('90');
 const bupa=page.locator('article').filter({has:page.getByRole('heading',{name:/Bupa acelera inversiones/})});
 await expect(bupa).toContainText('La Dehesa');await expect(bupa).toContainText('Clínicas Huinganal');await expect(bupa).toContainText('Mindplace en San Damián.');
 await expect(bupa).not.toContainText('…');
 await expect(bupa.locator('.card-meta')).toContainText('Publicado');
 await expect(bupa.locator('.card-meta')).not.toBeEmpty();
 const isapre=page.locator('article').filter({has:page.getByRole('heading',{name:/Pulso Isapre · datos/})});
 await expect(isapre.locator('.card-meta')).toContainText('Datos a 2026-07');
 await expect(isapre.locator('.card-meta')).not.toContainText('Publicado');
 await isapre.locator('[data-detail]').click();
 await expect(page.locator('#detailBody .intel').filter({hasText:'Muestra de datos validada'}).locator('li')).toHaveCount(1);
 await expect(page.locator('#detailBody')).toContainText('2026-06 → 2026-07');
 await expect(page.locator('#detailBody')).not.toContainText('No es variación mensual');
 await expect(page.locator('#detailBody .intel a').first()).toHaveAttribute('href',/superdesalud\.gob\.cl/);
 await page.getByRole('button',{name:'Cerrar resumen'}).click();
 const pulse=page.locator('article').filter({has:page.getByRole('heading',{name:/Pulso de sanciones a Prestadores/})});
 await expect(pulse).toContainText('Clínica Los Carrera · 70 UF · cheque en garantía');
 await pulse.locator('[data-detail]').click();await expect(page.locator('#detailBody')).toContainText('Resoluciones incluidas en este pulso · 3');
 const sourceBeforeDetails=await page.locator('#detailBody').evaluate(el=>el.querySelector('.sourceverify').compareDocumentPosition(el.querySelector('.intel'))&Node.DOCUMENT_POSITION_FOLLOWING);
 expect(sourceBeforeDetails).toBeTruthy();
 await expect(page.locator('#detailBody .sourceverify .related-item')).toHaveCount(3);
 await expect(page.locator('#detailBody')).toContainText('Clínica Redsalud Providencia · 200 UF');
 await page.getByRole('button',{name:'Cerrar resumen'}).click();
 const circular=page.locator('article').filter({has:page.getByRole('heading',{name:'Circular IF/N°535'})});
 await circular.locator('[data-detail]').click();await expect(page.locator('#detailBody')).toContainText('Circular IF/N°77');
 await page.locator('#detailBody .related').getByText('Normativa relacionada',{exact:false}).click();
 await expect(page.locator('#detailBody')).toContainText('Norma modificada');
 const ref=page.locator('#detailBody .related-item').filter({hasText:'Circular IF/N°77'});
 await expect(ref).toBeVisible();
 await expect(ref.getByText('Norma modificada',{exact:false})).toBeVisible();
 expect(await ref.locator('a').count()===1||await ref.getByText('enlace pendiente de verificación',{exact:false}).count()===1).toBeTruthy();
 await page.screenshot({path:`artifacts/${test.info().project.name}-cards-v2.png`,fullPage:true});
});
test('Global Intelligence keeps global facts, Chile hypotheses and PREMIUM distinct',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('link',{name:/Global Intelligence PREMIUM/})).toBeVisible();
 await page.getByRole('link',{name:/Global Intelligence PREMIUM/}).click();
 await expect(page.getByRole('heading',{name:'Global Intelligence'})).toBeVisible();
 await expect(page.locator('.premium-badge')).toHaveText('PREMIUM · muestra pública');
 await expect(page.getByText('El acceso exclusivo a PREMIUM aún no está activado.',{exact:false})).toBeVisible();
 await expect(page.locator('.theme')).toHaveCount(3);
 await expect(page.locator('.theme').first()).toContainText('Global Theme · research internacional');
 await expect(page.locator('.theme').first()).toContainText('Qué mirar en Chile · hipótesis, no evidencia local');
 await expect(page.locator('.theme').first()).toContainText('Trend Chile: no establecido');
 await expect(page.locator('.theme').first()).toContainText('señales locales compatibles verificadas: 0');
 await expect(page.locator('.source a')).toHaveCount(5);
 await expect(page.locator('.source a').filter({hasText:'PwC'})).toHaveAttribute('href',/^https:\/\/www\.pwc\.com\//);
 await expect(page.locator('.source a[href="https://www.who.int/publications/i/item/9789240122925"]')).toContainText(/^WHO ·/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(test.info().project.use.viewport.width+1);
 await page.screenshot({path:`artifacts/${test.info().project.name}-global-intelligence.png`,fullPage:true});
});
test('Weekly email capture requires consent and stays closed without approved provider',async({page})=>{
 await page.goto('/');
 await page.getByRole('link',{name:'Resumen semanal FREE →'}).click();
 await expect(page.getByRole('heading',{name:'Recibe lo importante, una vez por semana.'})).toBeVisible();
 await expect(page.locator('#email')).toBeDisabled();
 await expect(page.locator('#consent')).toBeDisabled();
 await expect(page.getByRole('button',{name:'Suscribirme'})).toBeDisabled();
 await expect(page.locator('#status')).toContainText('espera proveedor e información de privacidad aprobados');
 await expect(page.getByText('Si no hay material suficiente, no enviamos correo.')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(test.info().project.use.viewport.width+1);
 await page.screenshot({path:`artifacts/${test.info().project.name}-subscription.png`,fullPage:true});
});
test('analytics never sends without explicit privacy approval even if a key is present',async({page})=>{
 let attempts=0;
 await page.route('**/data/analytics.json',route=>route.fulfill({status:200,contentType:'application/json',
   body:JSON.stringify({enabled:true,privacy_approved:false,provider:'posthog',
     project_key:'public-test-key',host:'https://us.i.posthog.com'})}));
 await page.route('https://us.i.posthog.com/**',route=>{attempts++;return route.abort()});
 await page.goto('/');
 await page.getByRole('button',{name:'Personalizar mi radar'}).click();
 await page.locator('#period').selectOption('7');
 await expect(page.locator('#count')).toContainText('hallazgos');
 expect(attempts).toBe(0);
});
