const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let allSignals=[],activeType='Todos',activeScope='Todos',sortMode='date';
let previousVisit=localStorage.getItem('alicanto_last_visit');
let periodMode='7';
const readSet=new Set(JSON.parse(localStorage.getItem('alicanto_read')||localStorage.getItem('radar_read')||'[]'));
const interestState=JSON.parse(localStorage.getItem('alicanto_interests')||'{"types":[],"scopes":[]}');
const hiddenState=JSON.parse(localStorage.getItem('alicanto_hidden')||'{"types":[],"scopes":[]}');

function idFor(s){return btoa(unescape(encodeURIComponent((s.source_url||'')+'|'+(s.title||'')))).slice(0,120)}
function isRead(s){return readSet.has(idFor(s))}
function persistRead(){localStorage.setItem('alicanto_read',JSON.stringify([...readSet]))}
function arr(x){return Array.isArray(x)?x:[]}
function typeTags(s){return arr(s.signal_types)}
function scopeTags(s){return arr(s.scopes)}
function rel(score){const n=Number(score||0);if(n>=85)return{label:'Esencial',cls:'essential'};if(n>=65)return{label:'Relevante',cls:'relevant'};return{label:'Contexto',cls:'context'}}
function fmtDate(raw){if(!raw)return'';const d=new Date(raw);if(Number.isNaN(d.getTime()))return esc(raw);return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Santiago'}).format(d)}
function fmtUpdated(raw){const d=new Date(raw);if(Number.isNaN(d.getTime()))return'';const t=new Intl.DateTimeFormat('es-CL',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Santiago'}).format(d);return`Actualizado ${fmtDate(raw)}, ${t}`}
function tagHtml(s){return [...typeTags(s).map(x=>`<span class="tag">${esc(x)}</span>`),...scopeTags(s).slice(0,3).map(x=>`<span class="tag scope">${esc(x)}</span>`)].join('')}
function processHtml(s){const xs=arr(s.affected_processes);return xs.length?`<p class="affects"><span class="label">Impacta en:</span> ${xs.map(x=>`<span class="process">${esc(x)}</span>`).join(' ')}</p>`:''}
function listBlock(title,xs){return xs.length?`<div class="intel"><div class="intel-title">${title}</div><ul>${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}
function contextBlock(xs){if(!xs.length)return'';return`<details class="related"><summary>Contexto relacionado · ${xs.length}</summary>${xs.map(x=>`<div class="related-item"><div class="related-title">${esc(x.title||'Norma relacionada')}</div>${x.relationship?`<div class="relationship">${esc(x.relationship)}</div>`:''}${x.summary?`<div class="related-desc">${esc(x.summary)}</div>`:''}${x.event_date?`<div class="related-desc">Fecha: ${fmtDate(x.event_date)}</div>`:''}${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener">Ver antecedente ↗</a>`:''}</div>`).join('')}</details>`}
function sourceBlock(xs){if(!xs.length)return'';return`<details class="related sourceverify"><summary>Otras fuentes que verifican este hallazgo · ${xs.length}</summary>${xs.map(x=>`<div class="related-item"><div class="related-title">${esc(x.source_name||'Fuente')}</div><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title||'Ver publicación')} ↗</a></div>`).join('')}</details>`}
function card(s){const r=rel(s.radar_score),rd=isRead(s),id=idFor(s);return`<article id="sig-${esc(id)}" data-card="${esc(id)}" class="signal ${rd?'read':''}"><div class="cardhead"><div class="tagrow"><span class="priority ${r.cls}">${r.label}</span>${tagHtml(s)}</div><button class="readbtn ${rd?'done':''}" data-read="${esc(id)}">${rd?'↺ Marcar no leído':'✓ Marcar como leído'}</button></div><div class="body"><h2>${esc(s.title)}</h2>${s.what_happened?`<p><span class="label">Qué pasó:</span> ${esc(s.what_happened)}</p>`:''}${s.why_it_matters?`<p><span class="label">Por qué importa:</span> ${esc(s.why_it_matters)}</p>`:''}${processHtml(s)}${typeTags(s).includes('Normativa')?`<p><span class="label">Vigencia:</span> ${esc(s.validity_text||'No identificada automáticamente')}</p>`:''}${listBlock('Insights de datos',arr(s.data_insights).slice(0,3))}${listBlock('Puntos clave',arr(s.key_points).slice(0,3))}${listBlock('Aspectos a revisar',arr(s.risk_notes).slice(0,3))}<div class="source">${s.event_date?`Fecha de publicación: ${fmtDate(s.event_date)} · `:''}Fuente: ${esc(s.source_name||'')}${s.source_url?` · <a href="${esc(s.source_url)}" target="_blank" rel="noopener">Ver fuente original ↗</a>`:''}</div>${contextBlock(arr(s.related_context))}${sourceBlock(arr(s.source_alternatives))}</div></article>`}
function dateVal(s){return new Date(s.event_date||0).getTime()||0}
function ageDays(s){return Math.max(0,(Date.now()-dateVal(s))/86400000)}
function freshness(s){const a=ageDays(s);if(a<=1)return 100;if(a<=3)return 92;if(a<=7)return 80;if(a<=14)return 60;if(a<=30)return 40;return 18}
function interestScore(s){let score=0;for(const x of typeTags(s))if(interestState.types.includes(x))score+=10;for(const x of scopeTags(s))if(interestState.scopes.includes(x))score+=18;return Math.min(45,score)}
function personalizedScore(s){const radar=Number(s.radar_score||0),action=Number(s.actionability_score||radar);const impact=Math.max(Number(s.regulatory_impact_score||0),Number(s.economic_impact_score||0),Number(s.editorial_relevance||0));return .30*radar+.10*action+.12*impact+.28*freshness(s)+interestScore(s)}
function strategicTop(pool,n=4){return pool.filter(s=>!isRead(s)).sort((a,b)=>personalizedScore(b)-personalizedScore(a)||dateVal(b)-dateVal(a)).slice(0,n)}
function hidden(s){return typeTags(s).some(x=>hiddenState.types.includes(x))||scopeTags(s).some(x=>hiddenState.scopes.includes(x))}
function inPeriod(s){if(!s.event_date)return false;if(periodMode==='last'&&previousVisit)return dateVal(s)>new Date(previousVisit).getTime();return ageDays(s)<=Number(periodMode)+1}
function visible(){let out=allSignals.filter(inPeriod).filter(s=>!hidden(s)).filter(s=>(activeType==='Todos'||typeTags(s).includes(activeType))&&(activeScope==='Todos'||scopeTags(s).includes(activeScope)));if(sortMode==='date')out.sort((a,b)=>(isRead(a)-isRead(b))||dateVal(b)-dateVal(a)||Number(b.radar_score||0)-Number(a.radar_score||0));else out.sort((a,b)=>(isRead(a)-isRead(b))||personalizedScore(b)-personalizedScore(a)||dateVal(b)-dateVal(a));return out}
function trimSummary(s){let t=String(s.what_happened||'').trim();if(!t)t=s.why_it_matters||s.title;return t.length>230?t.slice(0,227).replace(/\s+\S*$/,'')+'…':t}
function briefLabel(s){const scope=scopeTags(s)[0],type=typeTags(s)[0];return [scope,type].filter(Boolean).join(' · ')||s.source_name||'Señal'}
function setReadWithoutReorder(s,value=true){const id=idFor(s);if(value)readSet.add(id);else readSet.delete(id);persistRead();const card=document.querySelector(`[data-card="${CSS.escape(id)}"]`);if(card){card.classList.toggle('read',value);const b=card.querySelector('[data-read]');if(b){b.classList.toggle('done',value);b.textContent=value?'↺ Marcar no leído':'✓ Marcar como leído'}}brief(visible())}
function openFromBrief(s){const id=idFor(s),el=document.getElementById(`sig-${id}`);if(!el)return;setReadWithoutReorder(s,true);el.classList.add('focus-card');el.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>el.classList.remove('focus-card'),3500)}
function brief(v){const top=strategicTop(v,4),unread=v.filter(s=>!isRead(s)).length,newCount=previousVisit?v.filter(s=>dateVal(s)>new Date(previousVisit).getTime()).length:0;document.getElementById('brief').innerHTML=`<section class="brief"><h2>Qué debes saber en 30 segundos que aún no has leído</h2><p class="briefmeta">${previousVisit?`<strong>${newCount}</strong> nuevas desde tu última visita · `:''}<strong>${unread}</strong> pendientes de leer en el período visible</p>${top.length?top.map((s,i)=>`<button class="briefitem" data-brief="${esc(idFor(s))}"><span class="briefnum">${i+1}</span><span><strong>${esc(briefLabel(s))}</strong><br>${esc(trimSummary(s))}<br><small>${esc(s.title)}</small></span></button>`).join(''):'<p class="muted">Estás al día.</p>'}<p class="muted">El resumen prioriza recencia, impacto e intereses. No fuerza diversidad por segmento.</p></section>`;document.querySelectorAll('[data-brief]').forEach(b=>b.onclick=()=>{const s=v.find(x=>idFor(x)===b.dataset.brief);if(s)openFromBrief(s)})}
function draw(){const v=visible();brief(v);document.getElementById('count').textContent=`${v.length} hallazgos visibles`;document.getElementById('local').innerHTML=v.map(card).join('');document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{const s=v.find(x=>idFor(x)===b.dataset.read);if(s)setReadWithoutReorder(s,!isRead(s))})}
function chips(id,values,current,setter){document.getElementById(id).innerHTML=values.map(v=>`<button class="chip ${v===current?'active':''}" data-v="${esc(v)}">${esc(v)}</button>`).join('');document.querySelectorAll(`#${id} .chip`).forEach(b=>b.onclick=()=>{setter(b.dataset.v);renderFilters();draw()})}
function renderFilters(){const types=['Todos',...['Normativa','Legal','Noticias','Datos','Fiscalización'].filter(x=>allSignals.some(s=>typeTags(s).includes(x)))];const scopes=['Todos',...new Set(allSignals.flatMap(scopeTags))];chips('typeFilters',types,activeType,v=>activeType=v);chips('scopeFilters',scopes,activeScope,v=>activeScope=v)}
function renderChoices(container,kind,vals,state,key){const make=vals.map(v=>`<label class="interestchip"><input type="checkbox" data-${key}="${kind}" value="${esc(v)}" ${state[kind].includes(v)?'checked':''}>${esc(v)}</label>`).join('');document.getElementById(container).innerHTML=make;document.querySelectorAll(`[data-${key}]`).forEach(el=>el.onchange=()=>{const k=el.dataset[key],v=el.value;if(el.checked&&!state[k].includes(v))state[k].push(v);if(!el.checked)state[k]=state[k].filter(x=>x!==v);localStorage.setItem(key==='interest'?'alicanto_interests':'alicanto_hidden',JSON.stringify(state));draw()})}
function renderPersonalization(){const types=['Normativa','Legal','Noticias','Datos','Fiscalización'];const scopes=[...new Set(allSignals.flatMap(scopeTags))].filter(Boolean);renderChoices('interestTypes','types',types,interestState,'interest');renderChoices('interestScopes','scopes',scopes,interestState,'interest');renderChoices('hiddenTypes','types',types,hiddenState,'hidden');renderChoices('hiddenScopes','scopes',scopes,hiddenState,'hidden')}
fetch('data/radar_today.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{document.getElementById('meta').textContent=fmtUpdated(d.generated_at);allSignals=d.signals||[];const period=document.getElementById('period');period.value=periodMode;document.getElementById('sort').value=sortMode;renderFilters();renderPersonalization();draw();period.onchange=e=>{periodMode=e.target.value;draw()};document.getElementById('sort').onchange=e=>{sortMode=e.target.value;draw()};document.getElementById('interestToggle').onclick=()=>document.getElementById('interests').classList.toggle('open');localStorage.setItem('alicanto_last_visit',new Date().toISOString())}).catch(()=>document.getElementById('local').innerHTML='<div>No se pudo cargar Alicanto.</div>');
