const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('web/app.js','utf8').split("fetch('data/radar_today.json'")[0];
function context(){const c={localStorage:{getItem:()=>null,setItem:()=>{}},btoa:s=>Buffer.from(s,'binary').toString('base64'),unescape,encodeURIComponent,Intl,Date,Set,Map};vm.createContext(c);vm.runInContext(source,c);return c}
test('full card IDs do not collide for long URLs',()=>{const c=context();assert.notEqual(c.idFor({source_url:'https://example.org/'+ 'a'.repeat(160)+'1'}),c.idFor({source_url:'https://example.org/'+ 'a'.repeat(160)+'2'}))});
test('date-only publication keeps calendar date in Chile',()=>{const c=context();assert.match(c.fmtDate('2026-09-23'),/23/)});
test('Signal Density defaults and fiscalizacion',()=>{const c=context();assert.equal(vm.runInContext('periodMode',c),'14');assert.equal(vm.runInContext('sortMode',c),'date');assert.match(source,/Fiscalización/);assert.match(fs.readFileSync('web/index.html','utf8'),/<option value="14" selected>14 días<\/option>/)});
test('BACKFILL never counts as new since visit',()=>{const c=context();vm.runInContext("periodMode='last';previousVisit='2026-09-22T00:00:00Z'",c);assert.equal(c.inPeriod({ingestion_mode:'BACKFILL',event_date:'2026-09-23',detected_at:'2026-09-23T12:00:00Z'}),false);assert.equal(c.inPeriod({ingestion_mode:'LIVE',event_date:'2026-09-23',detected_at:'2026-09-23T12:00:00Z'}),true)});

test('coverage counts never invent LIVE or BACKFILL when queue has not run',()=>{const c=context();const msg=c.coverageText({sources:{one:{}},queue:null,queue_status:'awaiting_first_global_discovery'});assert.match(msg,/sin medición global/);assert.doesNotMatch(msg,/0 LIVE/)});
test('coverage separates LIVE funnel and historical queue',()=>{const c=context();const msg=c.coverageText({sources:{one:{status:'ok'},two:{status:'error'}},queue_status:'measured',queue:{live_pending:2,backfill_pending:37,rejected:6},coverage_live:{detected:10,evaluated:8,selected:3}});assert.match(msg,/1 fuentes activas/);assert.match(msg,/10 señales detectadas · 8 evaluadas · 3 seleccionadas/)});
test('active source counts technical availability even when editorial outcome is warning',()=>{const c=context();const msg=c.coverageText({sources:{a:{technical_status:'ok',status:'warning'},b:{technical_status:'ok',status:'ok'},c:{technical_status:'error',status:'error'}},queue_status:'measured',queue:{},coverage_live:{detected:0,evaluated:0,selected:0}});assert.match(msg,/2 fuentes activas/)});
test('sanction pulse lists resolutions rather than corroborating sources',()=>{const c=context();assert.match(c.sourceBlock([{title:'Acto 1',url:'https://example.org/1'}],true),/Resoluciones incluidas en este pulso/)});
test('read status survives DF headline and teaser separation',()=>{const c=context();vm.runInContext("allSignals=[{source_url:'https://df.cl/example',title:'Titular',source_title_full:'Titular El plan incluye detalles'}]",c);vm.runInContext("readSet.add(idFor({source_url:'https://df.cl/example',title:'Titular El plan incluye detalles'}));migrateReads()",c);assert.equal(vm.runInContext('isRead(allSignals[0])',c),true)});
test('Cards V2 does not pretend depth from a headline or duplicate summary',()=>{const c=context();const shallow={title:'Un titular',what_happened:'Un titular',why_it_matters:'Un titular',source_url:'https://example.org'};assert.equal(c.cardDepth(shallow),false);const html=c.card(shallow);assert.doesNotMatch(html,/data-detail|Qué pasó:|Por qué importa:/);assert.match(html,/Fuente original/);assert.equal(c.cardDepth({...shallow,what_happened:'Detalle nuevo y confirmado que cambia el cuadro para los actores involucrados.',key_points:['Otra cifra material comprobada']}),true)});
test('limited evidence never gains a detail action from length or generic impact',()=>{const c=context();const shallow={title:'Anuncio',what_happened:'El anuncio no entrega detalles sobre alcance, vigencia ni ejecución. '.repeat(6),why_it_matters:'Puede interesar',affected_processes:['Prestaciones'],risk_notes:['No se informaron detalles']};assert.equal(c.detailKind(shallow),null);assert.doesNotMatch(c.card(shallow),/data-detail/);assert.equal(c.detailKind({...shallow,source_alternatives:[{title:'Resolución 1',url:'https://example.org'}]}),'context')});
test('negative evidence and repeated importance are not executive findings',()=>{const c=context();const s={title:'Anuncio',what_happened:'Se anunció una medida',why_it_matters:'Afectaría a prestadores'};assert.equal(c.detailKind({...s,key_points:['La fuente no especifica el alcance, la inversión ni los plazos de implementación.']}),null);assert.equal(c.detailKind({...s,key_points:[s.why_it_matters]}),null)});
test('one preference model, all included until explicitly unchecked',()=>{const c=context();const html=fs.readFileSync('web/index.html','utf8');assert.match(html,/Todo viene incluido\. Desmarca lo que no quieras ver\./);assert.doesNotMatch(html,/Ocultar tipos|Prioriza tus intereses/);assert.doesNotMatch(source,/interestScore\(/);assert.match(source,/!interestState\[kind\]\.includes\(v\)\?'checked'/)});
test('card never cuts a Bupa announcement in the middle of its meaning',()=>{const c=context();const s={title:'Bupa acelera inversiones',what_happened:'Bupa anunció tres proyectos por US$15 millones: abrirá un centro en La Dehesa, comprará Clínicas Huinganal y abrirá Mindplace en San Damián.',why_it_matters:'Incorpora capacidad ambulatoria y salud mental en el sector oriente mediante inversión y compra.'};const html=c.card(s);assert.match(html,/Huinganal y abrirá Mindplace en San Damián\./);assert.match(html,/inversión y compra\./);assert.doesNotMatch(html,/\.\.\.|…/);assert.doesNotMatch(fs.readFileSync('web/index.html','utf8'),/-webkit-line-clamp/)});
test('sanction pulse lists every material resolution including anchor',()=>{const c=context();const links=[1,2,3].map(i=>({title:`Resolución IP/N°${i} - Emisión: 08/09/2026`,material:`Clínica ${i} · 70 UF · cheque en garantía`,url:`https://example.org/${i}`}));const s={title:'Pulso sanciones',what_happened:'3 sanciones registradas.',why_it_matters:'Fiscalización reciente.',sanction_count:3,source_alternatives:links,source_url:links[0].url};const html=c.detailHtml(s);assert.equal((html.match(/Clínica \d · 70 UF/g)||[]).length,3);assert.doesNotMatch(html,/3 sanciones registradas; 2 resoluciones/)});
test('card metadata does not confuse resolution, data period and publication dates',()=>{const c=context();const sanction=c.cardMetadata({sanction_count:3,event_date:'2026-09-15',source_name:'Superintendencia de Salud'});assert.match(sanction,/Publicado 15/);assert.doesNotMatch(sanction,/Resolución más reciente/);const data=c.cardMetadata({event_type:'DATA_PULSE',data_period:'2026-07',event_date:'2026-07-31',source_name:'Superintendencia de Salud'});assert.match(data,/Datos a 2026-07/);assert.match(data,/Publicación no verificada/);assert.doesNotMatch(data,/Publicado 31/)});
test('unverified Circular 77 relation remains visible without invented URL',()=>{const c=context();const html=c.contextBlock([{title:'Circular IF/N°77',relationship:'Norma modificada',url:null,verified:false}]);assert.match(html,/Normativa relacionada/);assert.match(html,/Circular IF\/N°77/);assert.match(html,/Norma modificada/);assert.match(html,/enlace pendiente de verificación/);assert.doesNotMatch(html,/href=/)});
test('Global Intelligence is a separate PREMIUM surface with explicit Chile hypothesis',()=>{const html=fs.readFileSync('web/global.html','utf8'),js=fs.readFileSync('web/global.js','utf8'),data=JSON.parse(fs.readFileSync('web/data/global_themes.json','utf8'));assert.match(html,/PREMIUM/);assert.match(js,/hipótesis, no evidencia local/);assert.match(fs.readFileSync('web/app.js','utf8'),/Global Intelligence <strong>PREMIUM/);assert.ok(data.themes.every(t=>t.kind==='global_theme'&&t.chile_watch.kind==='hypothesis'&&t.chile_watch.trend_chile_status==='not_established'))});
