// Preferences stay on this device. No personal usage data is transmitted.
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function saveLocal(key,value){try{localStorage.setItem(key,value)}catch{}}
function coverageText(d){
 const sources=Object.values(d.sources||{}),live=d.coverage_live;
 const fmt=n=>new Intl.NumberFormat('es-CL').format(n);
 return d.queue_status==='measured'&&d.queue&&live
  ?`Hoy tenemos: ${fmt(sources.filter(s=>s.technical_status==='ok'||(!s.technical_status&&['ok','warning'].includes(s.status))).length)} fuentes activas · ${fmt(live.detected)} señales detectadas · ${fmt(live.evaluated)} evaluadas · ${fmt(live.selected)} seleccionadas (LIVE, portada actual).${d.discovery?.failed_sources?` Medición parcial: ${fmt(d.discovery.failed_sources)} fuentes con error.`:''}`
  :`${fmt(sources.length)} fuentes registradas · señales LIVE: aún sin medición global.`;
}
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let allSignals=[],activeType='Todos',activeScope='Todos',sortMode='date';
let previousVisit;try{previousVisit=localStorage.getItem('alicanto_last_visit')}catch{}
let periodMode='14';
const readStored=stored('alicanto_read',stored('radar_read',[]));
const readSet=new Set(Array.isArray(readStored)?readStored:[]);
const interestStored=stored('alicanto_interests',{});
const interestState=interestStored&&typeof interestStored==='object'&&!Array.isArray(interestStored)?interestStored:{};
for(const k of ['types','scopes','hiddenTypes','hiddenScopes'])if(!Array.isArray(interestState[k]))interestState[k]=[];
function idFor(s){return btoa(unescape(encodeURIComponent((s.source_url||'')+'|'+(s.title||''))))}
// Retain legacy reads only when their old ID identifies one unique signal.
function migrateReads(){const groups=new Map();for(const s of allSignals){const id=idFor(s),old=id.slice(0,120);groups.set(old,[...(groups.get(old)||[]),id]);if(s.source_title_full){const previous=idFor({...s,title:s.source_title_full});if(readSet.has(previous))readSet.add(id)}}for(const [old,ids] of groups)if(readSet.has(old)&&ids.length===1)readSet.add(ids[0])}
function isRead(s){return readSet.has(idFor(s))}
function persistRead(){saveLocal('alicanto_read',JSON.stringify([...readSet]))}
function arr(x){return Array.isArray(x)?x:[]}
function typeTags(s){return arr(s.signal_types)} function scopeTags(s){return arr(s.scopes)}
function rel(score){const n=Number(score||0);if(n>=85)return{label:'Esencial',cls:'essential'};if(n>=65)return{label:'Relevante',cls:'relevant'};return{label:'Contexto',cls:'context'}}
function fmtDate(raw){if(!raw)return'';const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(raw)?raw+'T12:00:00Z':raw);if(Number.isNaN(d.getTime()))return esc(raw);return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Santiago'}).format(d)}
function fmtUpdated(raw){const d=new Date(raw);if(Number.isNaN(d.getTime()))return'';const t=new Intl.DateTimeFormat('es-CL',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Santiago'}).format(d);return`Portada generada ${fmtDate(raw)}, ${t} · la fecha no indica una nueva revisión de las fuentes`}
function tagHtml(s){return [...typeTags(s).map(x=>`<span class="tag">${esc(x)}</span>`),...scopeTags(s).slice(0,3).map(x=>`<span class="tag scope">${esc(x)}</span>`)].join('')}
function processHtml(s){const xs=arr(s.affected_processes);return xs.length?`<p class="affects"><span class="label">Impacta en:</span> ${xs.map(x=>`<span class="process">${esc(x)}</span>`).join(' ')}</p>`:''}
function listBlock(title,xs){return xs.length?`<div class="intel"><div class="intel-title">${title}</div><ul>${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}
function contextBlock(xs){if(!xs.length)return'';return`<details class="related"><summary>Contexto relacionado · ${xs.length}</summary>${xs.map(x=>`<div class="related-item"><div class="related-title">${esc(x.title||'Norma relacionada')}</div>${x.relationship?`<div class="relationship">${esc(x.relationship)}</div>`:''}${x.summary?`<div class="related-desc">${esc(x.summary)}</div>`:''}${x.event_date?`<div class="related-desc">Fecha: ${fmtDate(x.event_date)}</div>`:''}${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener">Ver antecedente ↗</a>`:''}</div>`).join('')}</details>`}
function sourceBlock(xs,isPulse=false){if(!xs.length)return'';return`<details class="related sourceverify"><summary>${isPulse?'Resoluciones incluidas en este pulso':'Otras fuentes que verifican este hallazgo'} · ${xs.length}</summary>${xs.map(x=>`<div class="related-item"><div class="related-title">${esc(x.source_name||'Fuente')}</div><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title||'Ver publicación')} ↗</a></div>`).join('')}</details>`}
function distinct(a,b){const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();const x=norm(a),y=norm(b);return !!x&&x!==y&&!(x.startsWith(y)&&x.length-y.length<35)&&!(y.startsWith(x)&&y.length-x.length<35)}
function substantivePoints(s){return arr(s.key_points).filter(x=>distinct(x,s.what_happened)&&distinct(x,s.title)&&distinct(x,s.why_it_matters)&&!/(no (se )?(inform[aó]|entreg[aó]|detall[aó]|especific[aó]|precis[aó])|sin detalles|no hay detalles|falta(n)? detalles)/i.test(x))}
function detailKind(s){if(substantivePoints(s).length||arr(s.data_insights).length)return 'summary';if(arr(s.related_context).length||arr(s.source_alternatives).length)return 'context';return null}
function cardDepth(s){return detailKind(s)!==null}
function detailHtml(s){
 const facts=substantivePoints(s);
 const why=distinct(s.why_it_matters,s.what_happened)&&distinct(s.why_it_matters,s.title);
 const what=distinct(s.what_happened,s.title);
 return `<h2 id="detailTitle">${esc(s.title)}</h2>${what?`<p><strong>Qué ocurrió:</strong> ${esc(s.what_happened)}</p>`:''}${facts.length?listBlock('Hallazgos principales',facts):''}${arr(s.data_insights).length?listBlock('Cifras y lectura de datos',arr(s.data_insights)):''}${processHtml(s)}${why?`<p><strong>Implicancias:</strong> ${esc(s.why_it_matters)}</p>`:''}${s.validity_text?`<p><strong>Vigencia:</strong> ${esc(s.validity_text)}</p>`:''}${listBlock('Puntos que requieren atención',arr(s.risk_notes))}${contextBlock(arr(s.related_context))}${sourceBlock(arr(s.source_alternatives),Boolean(s.sanction_count))}<p class="source">${s.event_date?`Fecha de publicación: ${fmtDate(s.event_date)} · `:''}Fuente: ${esc(s.source_name||'')} · <a href="${esc(s.source_url||'')}" target="_blank" rel="noopener">Fuente original ↗</a></p>`
}
function card(s){const r=rel(s.radar_score),rd=isRead(s),id=idFor(s),depth=detailKind(s);return`<article id="sig-${esc(id)}" data-card="${esc(id)}" class="signal ${rd?'read':''}"><div class="cardhead"><div class="tagrow"><span class="priority ${r.cls}">${r.label}</span>${tagHtml(s)}</div><button class="readbtn ${rd?'done':''}" data-read="${esc(id)}">${rd?'↺ Marcar no leído':'✓ Marcar como leído'}</button></div><div class="body"><h2>${esc(s.title)}</h2>${distinct(s.what_happened,s.title)&&distinct(s.what_happened,s.why_it_matters)?`<p><span class="label">Qué pasó:</span> ${esc(trimSummary(s))}</p>`:''}${distinct(s.why_it_matters,s.title)?`<p><span class="label">Por qué importa:</span> ${esc(shortLine(s.why_it_matters))}</p>`:''}<div class="card-actions">${depth?`<button type="button" data-detail="${esc(id)}">${depth==='summary'?'Ver resumen →':'Ver contexto disponible →'}</button>`:''}${s.source_url?`<a href="${esc(s.source_url)}" target="_blank" rel="noopener">Fuente original ↗</a>`:''}</div></div></article>`}
function shortLine(value,max=155){const t=String(value||'');return t.length>max?t.slice(0,max-1).replace(/\s+\S*$/,'')+'…':t}
function openDetail(s){const dialog=document.getElementById('signalDetail');document.getElementById('detailBody').innerHTML=detailHtml(s);dialog.showModal();dialog.querySelector('#closeDetail').focus()}

function dateVal(s){return new Date(s.event_date||0).getTime()||0}
function ageDays(s){return Math.max(0,(Date.now()-dateVal(s))/86400000)}
function freshness(s){const a=ageDays(s);if(a<=2)return 100;if(a<=7)return 88;if(a<=14)return 72;if(a<=30)return 48;if(a<=60)return 28;return 12}
function interestScore(s){let score=0;for(const x of typeTags(s))if(interestState.types.includes(x))score+=12;for(const x of scopeTags(s))if(interestState.scopes.includes(x))score+=20;return Math.min(52,score)}
function personalizedScore(s){const radar=Number(s.radar_score||0),action=Number(s.actionability_score||radar),scope=Number(s.scope_score||radar);const impact=Math.max(Number(s.regulatory_impact_score||0),Number(s.economic_impact_score||0),Number(s.editorial_relevance||0));return .39*radar+.11*action+.07*scope+.10*impact+.07*freshness(s)+interestScore(s)}
function strategicTop(pool,n=4){return pool.filter(s=>!isRead(s)).sort((a,b)=>personalizedScore(b)-personalizedScore(a)||dateVal(b)-dateVal(a)).slice(0,n)}
function periodPhrase(){if(periodMode==='last'&&previousVisit)return'desde tu última visita';return`en los últimos ${periodMode==='last'?7:periodMode} días`}
function inPeriod(s){if(!s.event_date)return false;if(periodMode==='last'&&previousVisit)return s.ingestion_mode==='LIVE'&&new Date(s.detected_at||0).getTime()>new Date(previousVisit).getTime();return ageDays(s)<=Number(periodMode==='last'?7:periodMode)}
function visible(){let out=allSignals.filter(inPeriod).filter(s=>!typeTags(s).some(x=>interestState.hiddenTypes.includes(x))&&!scopeTags(s).some(x=>interestState.hiddenScopes.includes(x))).filter(s=>(activeType==='Todos'||typeTags(s).includes(activeType))&&(activeScope==='Todos'||scopeTags(s).includes(activeScope)));if(sortMode==='date')out.sort((a,b)=>(isRead(a)-isRead(b))||dateVal(b)-dateVal(a));else out.sort((a,b)=>(isRead(a)-isRead(b))||personalizedScore(b)-personalizedScore(a)||dateVal(b)-dateVal(a));return out}
function trimSummary(s){let t=String(s.what_happened||'').trim();const title=String(s.title||'').trim();if(t.toLowerCase().startsWith(title.toLowerCase()))t=t.slice(title.length).replace(/^[\s:–—-]+/,'');if(!t)t=s.why_it_matters||title;return t.length>185?t.slice(0,182).replace(/\s+\S*$/,'')+'…':t}
function briefLabel(s){const scopes=scopeTags(s);return scopes[0]||typeTags(s)[0]||s.source_name||'Señal'}
function setReadWithoutReorder(s,value=true){const id=idFor(s);if(value)readSet.add(id);else readSet.delete(id);persistRead();const card=document.querySelector(`[data-card="${CSS.escape(id)}"]`);if(card){card.classList.toggle('read',value);const b=card.querySelector('[data-read]');if(b){b.classList.toggle('done',value);b.textContent=value?'↺ Marcar no leído':'✓ Marcar como leído'}}brief(visible())}
function openFromBrief(s){const id=idFor(s);const el=document.getElementById(`sig-${id}`);if(!el)return;setReadWithoutReorder(s,true);el.classList.add('focus-card');el.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>el.classList.remove('focus-card'),3500)}
function brief(v){const top=strategicTop(v,4),unread=v.filter(s=>!isRead(s)).length;const unmeasured=periodMode==='last'&&previousVisit&&allSignals.some(s=>!s.ingestion_mode||!s.detected_at);const empty=unmeasured?'No se puede verificar qué cambió desde tu última visita: parte del histórico no tiene fecha de detección. Usa 14 días para revisar las señales.':'Estás al día con las señales medidas en este período.';document.getElementById('brief').innerHTML=`<section class="brief"><h2>Qué debes saber en 30 segundos que aún no has leído</h2><p class="briefmeta"><strong>${unread}</strong> hallazgos no leídos ${esc(periodPhrase())}</p>${top.length?top.map((s,i)=>`<button class="briefitem" data-brief="${esc(idFor(s))}"><span class="briefnum">${i+1}</span><span><strong>${esc(briefLabel(s))}</strong><br>${esc(trimSummary(s))}</span></button>`).join(''):`<p class="muted">${empty}</p>`}${unmeasured&&top.length?'<p class="muted">El histórico sin fecha de detección no se cuenta como novedad.</p>':''}<p class="muted">Abre una señal para ir a su tarjeta. Quedará marcada como leída, pero no cambiará de posición mientras la estás revisando.</p></section>`;document.querySelectorAll('[data-brief]').forEach(b=>b.onclick=()=>{const s=v.find(x=>idFor(x)===b.dataset.brief);if(s)openFromBrief(s)})}
function draw(){const v=visible();brief(v);document.getElementById('count').textContent=`${v.length} hallazgos`;document.getElementById('local').innerHTML=v.map(card).join('');document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{const s=v.find(x=>idFor(x)===b.dataset.read);if(s)setReadWithoutReorder(s,!isRead(s))});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const s=v.find(x=>idFor(x)===b.dataset.detail);if(s)openDetail(s)})}
function chips(id,values,current,setter){document.getElementById(id).innerHTML=values.map(v=>`<button class="chip ${v===current?'active':''}" data-v="${esc(v)}">${esc(v)}</button>`).join('');document.querySelectorAll(`#${id} .chip`).forEach(b=>b.onclick=()=>{setter(b.dataset.v);renderFilters();draw()})}
function renderFilters(){const types=['Todos',...['Normativa','Legal','Noticias','Datos','Fiscalización'].filter(x=>allSignals.some(s=>typeTags(s).includes(x)))];const scopes=['Todos',...new Set(allSignals.flatMap(scopeTags))];chips('typeFilters',types,activeType,v=>activeType=v);chips('scopeFilters',scopes,activeScope,v=>activeScope=v)}
function renderInterests(){const types=['Normativa','Legal','Noticias','Datos','Fiscalización'];const scopes=[...new Set(allSignals.flatMap(scopeTags))].filter(Boolean);const make=(kind,vals)=>vals.map(v=>`<label class="interestchip"><input type="checkbox" data-interest="${kind}" value="${esc(v)}" ${interestState[kind].includes(v)?'checked':''}>${esc(v)}</label>`).join('');document.getElementById('interestTypes').innerHTML=make('types',types);document.getElementById('interestScopes').innerHTML=make('scopes',scopes);document.getElementById('hiddenTypes').innerHTML=make('hiddenTypes',types);document.getElementById('hiddenScopes').innerHTML=make('hiddenScopes',scopes);document.querySelectorAll('[data-interest]').forEach(el=>el.onchange=()=>{const k=el.dataset.interest,v=el.value;if(el.checked&&!interestState[k].includes(v))interestState[k].push(v);if(!el.checked)interestState[k]=interestState[k].filter(x=>x!==v);saveLocal('alicanto_interests',JSON.stringify(interestState));draw()})}
fetch('data/radar_today.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('snapshot');return r.json()}).then(d=>{document.getElementById('meta').textContent=fmtUpdated(d.generated_at);allSignals=d.signals||[];migrateReads();document.getElementById('sort').value=sortMode;const period=document.getElementById('period');period.value=periodMode;renderFilters();renderInterests();draw();period.onchange=e=>{periodMode=e.target.value;draw()};document.getElementById('sort').onchange=e=>{sortMode=e.target.value;draw()};document.getElementById('interestToggle').onclick=()=>document.getElementById('interests').classList.toggle('open');saveLocal('alicanto_last_visit',new Date().toISOString())}).catch(()=>document.getElementById('local').innerHTML='<div>No se pudo cargar Alicanto.</div>');

fetch('data/product.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('coverage');return r.json()}).then(d=>{
 const el=document.getElementById('coverageCounts');if(!el)return;
 el.textContent=coverageText(d);
}).catch(()=>{});

document.getElementById('closeDetail').onclick=()=>document.getElementById('signalDetail').close();
document.getElementById('signalDetail').onclick=e=>{if(e.target.id==='signalDetail')e.target.close()};
