const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let allSignals=[],activeType='Todos',activeScope='Todos',currentSort='date';

function relevanceLabel(score){const n=Number(score||0);if(n>=85)return{label:'Esencial',cls:'essential'};if(n>=65)return{label:'Relevante',cls:'relevant'};return{label:'Contexto',cls:'context'}}
function fmtDate(raw){if(!raw)return'';const d=new Date(raw);if(Number.isNaN(d.getTime()))return esc(raw);return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Santiago'}).format(d)}
function fmtUpdated(raw){if(!raw)return'';const d=new Date(raw);if(Number.isNaN(d.getTime()))return esc(raw);const now=new Date();const opt={timeZone:'America/Santiago'};const same=now.toLocaleDateString('es-CL',opt)===d.toLocaleDateString('es-CL',opt);const time=new Intl.DateTimeFormat('es-CL',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Santiago'}).format(d);return same?`Actualizado hoy, ${time}`:`Actualizado ${fmtDate(raw)}, ${time}`}
function arr(x){return Array.isArray(x)?x:[]}
function typeTags(s){return arr(s.signal_types).length?arr(s.signal_types):arr(s.display_types)}
function scopeTags(s){return arr(s.scopes).length?arr(s.scopes):arr(s.display_scopes)}
function tagHtml(s){return [...typeTags(s).slice(0,2).map(x=>`<span class="tag">${esc(x)}</span>`),...scopeTags(s).slice(0,2).map(x=>`<span class="tag scope">${esc(x)}</span>`)].join('')}

function evidenceBlock(s){
  const pts=arr(s.key_points).slice(0,3), risks=arr(s.risk_notes).slice(0,3), insights=arr(s.data_insights).slice(0,3);
  let html='';
  if(pts.length) html+=`<div class="intel"><div class="intel-title">Puntos clave</div><ul>${pts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;
  if(risks.length) html+=`<div class="intel"><div class="intel-title">Aspectos a revisar</div><ul>${risks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;
  if(insights.length) html+=`<div class="intel"><div class="intel-title">Insights de datos</div><ul>${insights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;
  return html;
}
function relatedSources(s){const sources=arr(s.related_sources);if(!sources.length)return'';return `<details class="related"><summary>Ver ${sources.length} fuentes relacionadas</summary><div class="related-list">${sources.map(src=>`<div class="related-item"><div class="related-title">${esc(src.title||'Fuente relacionada')}</div>${src.summary?`<div class="related-desc">${esc(src.summary)}</div>`:''}${src.event_date?`<div class="related-desc">Fecha de publicación: ${fmtDate(src.event_date)}</div>`:''}${src.url?`<a href="${esc(src.url)}" target="_blank" rel="noopener">Ver fuente ↗</a>`:''}</div>`).join('')}</div></details>`}
function card(s){const rel=relevanceLabel(s.radar_score??0);const grouped=s.grouped_count>1?`<span class="grouped">${esc(s.grouped_count)} publicaciones conectadas</span>`:'';const recency=s.recency_label?`<span class="recency">${esc(s.recency_label)}</span>`:'';return `<article class="signal"><div class="top"><span class="priority ${rel.cls}">${rel.label}</span><div class="body"><div class="tagrow">${tagHtml(s)}</div><div class="meta-tags">${grouped}${recency}</div><h2>${esc(s.title)}</h2>${s.what_happened?`<p><span class="label">Qué pasó:</span> ${esc(s.what_happened)}</p>`:''}${s.why_it_matters?`<p><span class="label">Por qué importa:</span> ${esc(s.why_it_matters)}</p>`:''}${typeTags(s).includes("Normativa")?`<p><span class="label">Vigencia:</span> ${esc(s.validity_text||"No identificada automáticamente")}</p>`:''}${evidenceBlock(s)}<div class="source">${s.event_date?`Fecha de publicación: ${fmtDate(s.event_date)} · `:''}Fuente: ${esc(s.source_name||'')}${s.source_url&&!arr(s.related_sources).length?` · <a href="${esc(s.source_url)}" target="_blank" rel="noopener">Ver fuente original ↗</a>`:''}</div>${relatedSources(s)}</div></div></article>`}
function dval(s){return new Date(s.event_date||0).getTime()||0}
function visible(){let out=allSignals.filter(s=>(activeType==='Todos'||typeTags(s).includes(activeType))&&(activeScope==='Todos'||scopeTags(s).includes(activeScope)));if(currentSort==='relevance')out.sort((a,b)=>(Number(b.radar_score)||0)-(Number(a.radar_score)||0)||dval(b)-dval(a));else out.sort((a,b)=>dval(b)-dval(a)||(Number(b.radar_score)||0)-(Number(a.radar_score)||0));return out}
function draw(){const v=visible();document.getElementById('count').textContent=v.length?`${v.length} hallazgos seleccionados`:'Sin hallazgos para estos filtros';document.getElementById('local').innerHTML=v.length?v.map(card).join(''):'<div class="empty">No hay hallazgos para esta combinación.</div>'}
function chips(id,values,current,setter){document.getElementById(id).innerHTML=values.map(v=>`<button class="chip ${v===current?'active':''}" data-v="${esc(v)}">${esc(v)}</button>`).join('');document.querySelectorAll(`#${id} .chip`).forEach(b=>b.addEventListener('click',()=>{setter(b.dataset.v);renderFilters();draw()}))}
function renderFilters(){const types=['Todos',...Array.from(new Set(allSignals.flatMap(typeTags))).sort()];const scopes=['Todos',...Array.from(new Set(allSignals.flatMap(scopeTags))).sort()];chips('typeFilters',types,activeType,v=>activeType=v);chips('scopeFilters',scopes,activeScope,v=>activeScope=v)}
fetch('data/radar_today.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{document.getElementById('meta').innerHTML=`<span>${fmtUpdated(d.generated_at)}</span>`;allSignals=(d.signals||[]).filter(x=>x.category!=='Radar Mundo');renderFilters();draw();document.getElementById('sort').addEventListener('change',e=>{currentSort=e.target.value;draw()})}).catch(()=>document.getElementById('local').innerHTML='<div class="empty">Todavía no se generó el Radar de hoy.</div>');
