// Preferences stay on this device. No personal usage data is transmitted.
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function saveLocal(key,value){try{localStorage.setItem(key,value)}catch{}}
function coverageText(d){
 const sources=Object.values(d.sources||{}),live=d.coverage_live;
 const fmt=n=>new Intl.NumberFormat('es-CL').format(n);
 return d.queue_status==='measured'&&d.queue&&live
  ?`Cobertura global auditada: ${fmt(sources.filter(s=>s.technical_status==='ok'||(!s.technical_status&&['ok','warning'].includes(s.status))).length)} fuentes activas · ${fmt(live.detected)} señales detectadas · ${fmt(live.evaluated)} evaluadas · ${fmt(live.selected)} seleccionadas (LIVE, portada actual).${d.discovery?.failed_sources?` Medición parcial: ${fmt(d.discovery.failed_sources)} fuentes con error.`:''}`
  :`Cobertura global aún no medida: ${fmt(sources.length)} fuentes registradas · señales LIVE sin medición global.`;
}
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const filterStored=stored('alicanto_filters',{});
let allSignals=[],activeType=filterStored.type||'Todos',activeScope=filterStored.scope||'Todos',sortMode=filterStored.sort||'date';
let freeValue={};
let previousVisit;try{previousVisit=localStorage.getItem('alicanto_last_visit')}catch{}
let periodMode=filterStored.period||'14';
const readStored=stored('alicanto_read',stored('radar_read',[]));
const readSet=new Set(Array.isArray(readStored)?readStored:[]);
if(!stored('alicanto_global_migrated',false)){const legacy=stored('alicanto_global_read',[]);if(Array.isArray(legacy))for(const id of legacy)readSet.add(`global:${id}`);saveLocal('alicanto_global_migrated',JSON.stringify(true));saveLocal('alicanto_read',JSON.stringify([...readSet]))}
function persistFilters(){saveLocal('alicanto_filters',JSON.stringify({type:activeType,scope:activeScope,period:periodMode,sort:sortMode}))}
function encodedId(value){return btoa(unescape(encodeURIComponent(value)))}
function idFor(s){return encodedId((s.source_url||'')+'|'+(s.event_date||'')+'|'+(s.event_type||'OTHER'))}
function legacyIdFor(s,title=s.title){return encodedId((s.source_url||'')+'|'+(title||''))}
function decodedId(value){try{return decodeURIComponent(escape(atob(value)))}catch{return''}}
// Migrate title-based IDs to the stable URL+event-date identity. This keeps a read
// state even when an audited headline changes, without relying on a guessed title.
function migrateReads(){const byKnown=new Map();for(const s of allSignals){const id=idFor(s);for(const old of [legacyIdFor(s),s.source_title_full?legacyIdFor(s,s.source_title_full):null,s.legacy_read_title?legacyIdFor(s,s.legacy_read_title):null].filter(Boolean)){byKnown.set(old,[...(byKnown.get(old)||[]),id]);byKnown.set(old.slice(0,120),[...(byKnown.get(old.slice(0,120))||[]),id])}}for(const [old,ids] of byKnown)if(readSet.has(old)&&new Set(ids).size===1)readSet.add(ids[0])}
function isRead(s){return readSet.has(idFor(s))}
function persistRead(){saveLocal('alicanto_read',JSON.stringify([...readSet]))}
function globalId(id){return `global:${id}`}
function specials(){const out=[],g=freeValue.global_teaser,w=freeValue.weekly_insight;if(g)out.push({kind:'global',id:globalId(g.theme_id),title:g.title,summary:g.excerpt,date:g.published_at,source:g.source_label||(g.publishers||[]).join(' · '),href:g.premium_href});if(w){const base=allSignals.find(s=>s.source_url===w.source_url);out.push({kind:'weekly',id:base?idFor(base):`weekly:${w.id}`,title:w.insight_title||w.title,summary:w.insight_teaser||w.insight_reading,date:w.event_date,source:w.source_name,href:w.source_url})}return out}
function specialRead(x){return readSet.has(x.id)}
function specialInPeriod(x){return periodMode!=='last'&&inPeriod({event_date:x.date})}
const checkIcon='<svg class="action-icon" aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle><path d="m8 12 2.5 2.5L16 9"></path></svg>';
const unreadIcon='<svg class="action-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M5 9V4m0 0h5M5 4l3.6 3.6A7 7 0 1 1 5.7 15"></path></svg>';
const shareIcon='<svg class="action-icon" aria-hidden="true" viewBox="0 0 24 24"><circle cx="18" cy="5" r="2.5"></circle><circle cx="6" cy="12" r="2.5"></circle><circle cx="18" cy="19" r="2.5"></circle><path d="m8.2 10.8 7.6-4.5M8.2 13.2l7.6 4.5"></path></svg>';
function readAction(read){return `${read?unreadIcon:checkIcon}<span class="read-label">${read?'No leído':'Leído'}</span>`}
function shareAction(targetId,title){return `<button type="button" class="sharebtn" data-share="${esc(targetId)}" data-share-title="${esc(title)}" aria-label="Compartir: ${esc(title)}" title="Compartir">${shareIcon}<span>Compartir</span></button><span class="share-feedback" role="status" aria-live="polite"></span>`}
function specialCard(x){const read=specialRead(x),actionLabel=read?'Marcar como no leído':'Marcar como leído';return `<article id="special-${esc(x.id)}" tabindex="-1" class="signal special ${x.kind} ${read?'read':''}" data-special="${esc(x.id)}"><div class="cardhead"><span class="special-label">${x.kind==='global'?'Global Intelligence · análisis internacional':'Insight Alicanto · lectura semanal'}</span><div class="card-status-actions"><button type="button" class="readbtn ${read?'done':''}" data-special-read="${esc(x.id)}" aria-label="${actionLabel}" title="${actionLabel}">${readAction(read)}</button>${shareAction(`special-${x.id}`,x.title)}</div></div><div class="body"><h2>${esc(x.title)}</h2><p>${esc(x.summary)}</p><div class="card-actions"><button type="button" data-special-open="${esc(x.id)}">${x.kind==='global'?'Ver análisis →':'Ver insight →'}</button></div><div class="card-meta">${fmtBriefDate(x.date)} · ${esc(x.source)}</div></div></article>`}
function openSpecial(x){setSpecialRead(x,true);if(x.kind==='global')location.href=x.href;else document.getElementById('weeklyInsightDialog').showModal()}
function setSpecialRead(x,value){const hadFocus=document.activeElement?.dataset.specialRead===x.id;if(value)readSet.add(x.id);else readSet.delete(x.id);persistRead();draw();if(hadFocus)document.querySelector(`[data-special-read="${CSS.escape(x.id)}"]`)?.focus()}
function arr(x){return Array.isArray(x)?x:[]}
function typeTags(s){return arr(s.signal_types)} function scopeTags(s){return arr(s.scopes)}
function rel(score){const n=Number(score||0);if(n>=85)return{label:'Esencial',cls:'essential'};if(n>=65)return{label:'Relevante',cls:'relevant'};return{label:'Contexto',cls:'context'}}
function fmtDate(raw){if(!raw)return'';const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(raw)?raw+'T12:00:00Z':raw);if(Number.isNaN(d.getTime()))return esc(raw);return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Santiago'}).format(d)}
function fmtBriefDate(raw){if(!raw)return'';const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(raw)?raw+'T12:00:00Z':raw);if(Number.isNaN(d.getTime()))return String(raw);return new Intl.DateTimeFormat('es-CL',{day:'numeric',month:'short',timeZone:'America/Santiago'}).format(d).replace(/^(\d{1,2})-(?=\p{L})/u,'$1 ').replace(/\.$/,'')}
function briefSource(x){return x.kind==='weekly'&&x.source==='Superintendencia de Salud'?'SIS':String(x.source||'').replace(/\s*[·+]\s*/g,' + ')}
function fmtUpdated(raw){const d=new Date(raw);if(Number.isNaN(d.getTime()))return'';const t=new Intl.DateTimeFormat('es-CL',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Santiago'}).format(d);return`Última actualización: ${fmtDate(raw)}, ${t}`}
function tagHtml(s){return [...typeTags(s).map(x=>`<span class="tag">${esc(x)}</span>`),...scopeTags(s).slice(0,3).map(x=>`<span class="tag scope">${esc(x)}</span>`)].join('')}
function processHtml(s){const xs=arr(s.affected_processes);return xs.length?`<p class="affects"><span class="label">Impacta en:</span> ${xs.map(x=>`<span class="process">${esc(x)}</span>`).join(' ')}</p>`:''}
function listBlock(title,xs){return xs.length?`<div class="intel"><div class="intel-title">${title}</div><ul>${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}
function insightBlock(s){const xs=arr(s.data_insight_evidence);if(!xs.length)return listBlock('Cifras y lectura de datos',arr(s.data_insights));return `<div class="intel"><div class="intel-title">Muestra de datos validada · período, cálculo y evidencia</div><ul>${xs.map(x=>`<li>${esc(x.text)}<div class="related-desc">${esc(x.period)} · ${esc(x.formula)} · ${esc(x.sheet)} · <a href="${esc(x.source_url)}" target="_blank" rel="noopener">Serie oficial ↗</a></div></li>`).join('')}</ul></div>`}
function contextBlock(xs){if(!xs.length)return'';return`<details class="related"><summary>Normativa relacionada · ${xs.length}</summary>${xs.map(x=>`<div class="related-item"><div class="related-title">${esc(x.title||'Norma relacionada')}</div>${x.relationship?`<div class="relationship">${esc(x.relationship)}</div>`:''}${x.summary?`<div class="related-desc">${esc(x.summary)}</div>`:''}${x.event_date?`<div class="related-desc">Fecha: ${fmtDate(x.event_date)}</div>`:''}${x.url&&x.verified?`<a href="${esc(x.url)}" target="_blank" rel="noopener">Ver antecedente ↗</a>`:'<div class="related-desc">Referencia identificada en la fuente · enlace pendiente de verificación</div>'}</div>`).join('')}</details>`}
function sourceBlock(xs,isPulse=false,isData=false){if(!xs.length)return'';return`<details class="related sourceverify"><summary>${isData?'Series oficiales incluidas':isPulse?'Resoluciones incluidas en este pulso':'Otras fuentes que verifican este hallazgo'} · ${xs.length}</summary>${xs.map(x=>`<div class="related-item"><div class="related-title">${esc(x.material||x.source_name||'Fuente')}</div><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title||'Ver publicación')} ↗</a>${x.event_date?`<div class="related-desc">Publicado ${fmtDate(x.event_date)}</div>`:''}</div>`).join('')}</details>`}
function enrichmentBlock(xs,historical,status){if(!xs.length&&!historical.length&&!status)return'';return`<details class="related editorial-enrichment"><summary>Enriquecimiento editorial · ${xs.length}</summary>${xs.map(x=>`<div class="related-item"><div class="relationship">${esc(x.label)}</div><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title)} ↗</a><div class="related-desc">${esc(x.note)}</div></div>`).join('')}${historical.length?`<div class="intel-title">Conexiones históricas</div>${historical.map(x=>`<div class="related-item"><div class="relationship">${esc(x.label)}</div><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title)} ↗</a>${x.event_date?`<div class="related-desc">Publicado ${fmtDate(x.event_date)}</div>`:''}<div class="related-desc">${esc(x.note)}</div></div>`).join('')}`:''}${status?`<div class="related-desc">Contexto histórico: ${esc(status)}</div>`:''}</details>`}
function distinct(a,b){const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();const x=norm(a),y=norm(b);return !!x&&x!==y&&!(x.startsWith(y)&&x.length-y.length<35)&&!(y.startsWith(x)&&y.length-x.length<35)}
function substantivePoints(s){return arr(s.key_points).filter(x=>distinct(x,s.what_happened)&&distinct(x,s.title)&&distinct(x,s.why_it_matters)&&!/(no (se )?(inform[aó]|entreg[aó]|detall[aó]|especific[aó]|precis[aó])|sin detalles|no hay detalles|falta(n)? detalles)/i.test(x))}
function detailKind(s){if(substantivePoints(s).length||arr(s.data_insights).length)return 'summary';if(arr(s.related_context).length||arr(s.source_alternatives).length||arr(s.editorial_enrichment).length||arr(s.historical_connections).length)return 'context';return null}
function cardDepth(s){return detailKind(s)!==null}
function detailHtml(s){
 const facts=substantivePoints(s);
 const reviewedTitle=triageTitle(s),reviewedWhat=s.card_what||s.what_happened,reviewedWhy=s.card_why||s.why_it_matters;
 const why=distinct(reviewedWhy,reviewedWhat)&&distinct(reviewedWhy,reviewedTitle);
 const what=distinct(reviewedWhat,reviewedTitle);
 const timing=s.data_period?`Período de datos: ${esc(s.data_period)} · ${s.event_date?`Fecha de publicación: ${fmtDate(s.event_date)} · `:'Fecha de publicación no verificada · '}${s.validation_date?`Validado: ${fmtDate(s.validation_date)} · `:''}`:s.event_date?`Fecha de publicación: ${fmtDate(s.event_date)} · `:'';
 return `<h2 id="detailTitle">${esc(reviewedTitle)}</h2>${what?`<p><strong>Qué ocurrió:</strong> ${esc(reviewedWhat)}</p>`:''}${contextBlock(arr(s.related_context))}${s.sanction_count&&arr(s.source_alternatives).length!==s.sanction_count?`<p class="muted">${s.sanction_count} sanciones registradas; ${arr(s.source_alternatives).length} resoluciones con enlace disponible.</p>`:''}${sourceBlock(arr(s.source_alternatives),Boolean(s.sanction_count),s.event_type==='DATA_PULSE')}${enrichmentBlock(arr(s.editorial_enrichment),arr(s.historical_connections),s.historical_context_status)}${facts.length?listBlock('Hallazgos principales',facts):''}${insightBlock(s)}${processHtml(s)}${why?`<p><strong>Implicancias:</strong> ${esc(reviewedWhy)}</p>`:''}${s.validity_text?`<p><strong>Vigencia:</strong> ${esc(s.validity_text)}</p>`:''}${listBlock('Puntos que requieren atención',arr(s.risk_notes))}<p class="source">${timing}Fuente: ${esc(s.source_name||'')}${s.source_url?` · <a href="${esc(s.source_url)}" target="_blank" rel="noopener">Fuente original ↗</a>`:''}</p>`
}
function cardMetadata(s){const dataPulse=s.event_type==='DATA_PULSE'&&s.data_period;const date=dataPulse?`Datos a ${esc(s.data_period)} · ${s.event_date?`Publicado ${fmtDate(s.event_date)}`:'Publicación no verificada'}${s.validation_date?` · Validado ${fmtDate(s.validation_date)}`:''}`:s.event_date?`Publicado ${fmtDate(s.event_date)}`:'Fecha de publicación no verificada';return `${date}${s.source_name?` · ${esc(s.source_name)}`:''}`}
function card(s){const r=rel(s.radar_score),rd=isRead(s),id=idFor(s),depth=detailKind(s),title=triageTitle(s),enrichmentOnly=depth==='context'&&arr(s.editorial_enrichment).length&&!arr(s.related_context).length&&!arr(s.source_alternatives).length,actionLabel=rd?'Marcar como no leído':'Marcar como leído';return`<article id="sig-${esc(id)}" tabindex="-1" data-card="${esc(id)}" class="signal ${rd?'read':''}"><div class="cardhead"><div class="tagrow"><span class="priority ${r.cls}">${r.label}</span>${tagHtml(s)}</div><div class="card-status-actions"><button class="readbtn ${rd?'done':''}" data-read="${esc(id)}" aria-label="${actionLabel}" title="${actionLabel}">${readAction(rd)}</button>${shareAction(`sig-${id}`,title)}</div></div><div class="body"><h2>${esc(title)}</h2>${title!==s.title?`<span class="sr-only">Titular original: ${esc(s.title)}</span>`:''}${distinct(s.what_happened,s.title)&&distinct(s.what_happened,s.why_it_matters)?`<p><span class="label">Qué pasó:</span> ${esc(trimSummary(s))}</p>`:''}${distinct(s.why_it_matters,s.title)?`<p><span class="label">Por qué importa:</span> ${esc(s.card_why||firstComplete(s.why_it_matters))}</p>`:''}<div class="card-actions">${depth?`<button type="button" data-detail="${esc(id)}">${depth==='summary'?'Ver resumen →':'Ver contexto disponible →'}</button>`:''}${s.source_url&&!enrichmentOnly?`<a href="${esc(s.source_url)}" target="_blank" rel="noopener">Fuente original ↗</a>`:''}<button class="back-brief" type="button" data-back-brief hidden>← Volver arriba</button></div><div class="card-meta">${cardMetadata(s)}</div></div></article>`}
function openDetail(s){const dialog=document.getElementById('signalDetail');document.getElementById('detailBody').innerHTML=detailHtml(s);dialog.showModal();dialog.querySelector('#closeDetail').focus()}

function dateVal(s){return new Date(s.event_date||0).getTime()||0}
function ageDays(s){return Math.max(0,(Date.now()-dateVal(s))/86400000)}
function freshness(s){const a=ageDays(s);if(a<=2)return 100;if(a<=7)return 88;if(a<=14)return 72;if(a<=30)return 48;if(a<=60)return 28;return 12}
function personalizedScore(s){const radar=Number(s.radar_score||0),action=Number(s.actionability_score||radar),scope=Number(s.scope_score||radar);const impact=Math.max(Number(s.regulatory_impact_score||0),Number(s.economic_impact_score||0),Number(s.editorial_relevance||0));return .39*radar+.11*action+.07*scope+.10*impact+.07*freshness(s)}
function inboxPool(){const weekly=freeValue.weekly_insight,active=weekly&&activeType==='Todos'&&activeScope==='Todos'&&specialInPeriod({date:weekly.event_date});return visible().filter(s=>!isRead(s)&&!(active&&s.source_url===weekly.source_url)).sort((a,b)=>dateVal(b)-dateVal(a))}
function periodPhrase(){if(periodMode==='last'&&previousVisit)return'desde tu última visita';return`en los últimos ${periodMode==='last'?7:periodMode} días`}
function inPeriod(s){if(!s.event_date)return false;if(periodMode==='last'&&previousVisit)return s.ingestion_mode==='LIVE'&&new Date(s.detected_at||0).getTime()>new Date(previousVisit).getTime();return ageDays(s)<=Number(periodMode==='last'?7:periodMode)}
function visible(){let out=allSignals.filter(inPeriod).filter(s=>(activeType==='Todos'||typeTags(s).includes(activeType))&&(activeScope==='Todos'||scopeTags(s).includes(activeScope)));if(sortMode==='date')out.sort((a,b)=>(isRead(a)-isRead(b))||dateVal(b)-dateVal(a));else out.sort((a,b)=>(isRead(a)-isRead(b))||personalizedScore(b)-personalizedScore(a)||dateVal(b)-dateVal(a));return out}
function firstComplete(value){const text=String(value||'').trim(),match=text.match(/^(.+?[.!?])\s+(?=[A-ZÁÉÍÓÚ])/);return match&&match[1].length>=65?match[1]:text}
function trimSummary(s){let t=String(s.what_happened||'').trim();const title=String(s.title||'').trim();if(t.toLowerCase().startsWith(title.toLowerCase()))t=t.slice(title.length).replace(/^[\s:–—-]+/,'');if(!t)t=s.why_it_matters||title;return s.card_what||firstComplete(t)}
const verifiedTriageTitles={
 'https://www.superdesalud.gob.cl/normativa/circular-if-n535/':'Isapres: reembolsos públicos sin compensación de deudas · IF/N°535',
 'https://www.superdesalud.gob.cl/normativa/circular-if-n534/':'Isapres: bonos electrónicos con cédula si falla la biometría · IF/N°534',
 'https://www.minsal.cl/ministra-de-salud-presenta-piloto-para-que-pacientes-del-hospital-barros-luco-retiren-sus-medicamentos-en-farmacias-cercanas-a-sus-hogares-adheridas-a-ley-cenabast/':'Minsal prueba retiro de medicamentos del Barros Luco en farmacias Cenabast',
 'https://www.minsal.cl/consejo-para-mejorar-eficiencia-y-reducir-deficit-estructural-en-salud-incorpora-mirada-de-servicios-de-salud-y-hospitales-en-su-segunda-sesion/':'Minsal suma hospitales y Servicios de Salud al consejo sobre eficiencia y déficit',
 'https://www.df.cl/empresas/salud/max-luksic-propone-alianza-entre-municipalidades-para-mejorar-atencion':'Max Luksic propone alianza municipal para ejecutar recursos de atención primaria'
};
function triageTitle(s){const title=String(s.title||'').trim();if(s.editorial_review_id)return title;if(verifiedTriageTitles[s.source_url])return verifiedTriageTitles[s.source_url];if(/^(resolución|circular|decreto|oficio)\b/i.test(title)&&s.card_what)return firstComplete(s.card_what);if(title.length>95&&s.card_what&&s.card_what.length<title.length)return firstComplete(s.card_what);return title||firstComplete(s.card_what||s.what_happened||'Señal verificada')}
function triageSummary(s){const what=trimSummary(s),why=s.card_why||firstComplete(s.why_it_matters);return distinct(what,triageTitle(s))?what:why}
function setReadWithoutReorder(s,value=true){const id=idFor(s);if(value)readSet.add(id);else readSet.delete(id);persistRead();for(const card of document.querySelectorAll(`[data-card="${CSS.escape(id)}"],[data-special="${CSS.escape(id)}"]`)){card.classList.toggle('read',value);const b=card.querySelector('[data-read],[data-special-read]');if(b){const label=value?'Marcar como no leído':'Marcar como leído';b.classList.toggle('done',value);b.innerHTML=readAction(value);b.setAttribute('aria-label',label);b.title=label}}brief();updateMetrics(visible())}
function openFromBrief(s){const id=idFor(s);if(!document.getElementById(`sig-${id}`)){activeType='Todos';activeScope='Todos';renderFilters();draw()}const el=document.getElementById(`sig-${id}`);if(!el)return;setReadWithoutReorder(s,true);el.querySelector('[data-back-brief]').hidden=false;el.tabIndex=-1;el.focus({preventScroll:true});el.classList.add('focus-card');el.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>el.classList.remove('focus-card'),3500)}
function brief(){
 const specialItems=specials().filter(x=>specialInPeriod(x)&&!specialRead(x)&&activeType==='Todos'&&activeScope==='Todos').map(x=>({...x,date:x.date,source:x.source||''})).sort((a,b)=>({global:0,weekly:1}[a.kind]-({global:0,weekly:1}[b.kind])));
 const regularItems=inboxPool().map(s=>({id:idFor(s),title:triageTitle(s),summary:triageSummary(s),original:triageTitle(s)!==s.title?s.title:null,date:s.event_date,source:s.source_name||s.publisher||'',signal:s})).sort((a,b)=>new Date(b.date)-new Date(a.date));
 const items=[...specialItems,...regularItems],unmeasured=periodMode==='last'&&previousVisit&&allSignals.some(s=>!s.ingestion_mode||!s.detected_at);
 const empty=unmeasured?'No se puede verificar qué cambió desde tu última visita: parte del histórico no tiene fecha de detección. Usa 14 días para revisar las señales.':'Estás al día con las señales medidas en este período.';
 const host=document.getElementById('brief'),oldScroll=host.querySelector('.brief-list')?.scrollTop||0;
 host.innerHTML=`<div class="brief"><div class="brief-list">${items.length?items.map((x,i)=>`<div class="briefrow ${x.kind?'brief-'+x.kind:''}"><button class="briefitem" data-brief="${esc(x.id)}"><span class="briefnum">${i+1}</span><span>${x.kind?`<span class="brief-kind">${x.kind==='global'?'Global Intelligence':'Insight semanal'}</span><br>`:''}<strong>${esc(x.title)}</strong><span class="brief-meta">${fmtBriefDate(x.date)} · ${esc(briefSource(x))}</span><span class="triage-summary">${esc(x.summary)}${x.original?` · ${esc(x.original)}`:''}</span></span></button><button type="button" class="briefread" data-brief-read="${esc(x.id)}" aria-label="Marcar como leído: ${esc(x.title)}" title="Marcar como leído">${checkIcon}</button><details class="brief-context"><summary>Contexto de la señal</summary><p>${esc(x.summary)}</p></details></div>`).join(''):`<p class="muted">${empty}</p>`}</div>${items.length?`<div class="brief-continuation"><button type="button" data-brief-expand hidden>Ver todo en Ponte al día</button><button type="button" data-feed-cue>Continuar al feed ↓</button></div>`:''}${unmeasured&&items.length?'<p class="muted">El histórico sin fecha de detección no se cuenta como novedad.</p>':''}</div>`;
 const list=host.querySelector('.brief-list');if(list)list.scrollTop=oldScroll;
 const expand=host.querySelector('[data-brief-expand]');if(expand&&list)requestAnimationFrame(()=>{expand.hidden=!(matchMedia('(max-width: 760px)').matches&&list.scrollHeight>list.clientHeight+1)});
 host.querySelectorAll('[data-brief]').forEach(b=>b.onclick=()=>{const x=items.find(y=>y.id===b.dataset.brief);if(x?.signal)openFromBrief(x.signal);else if(x)openSpecial(x)});
 host.querySelectorAll('[data-brief-read]').forEach(b=>b.onclick=()=>{const x=items.find(y=>y.id===b.dataset.briefRead);if(!x)return;const at=[...host.querySelectorAll('[data-brief-read]')].indexOf(b);if(x.signal)setReadWithoutReorder(x.signal,true);else setSpecialRead(x,true);const next=host.querySelectorAll('[data-brief-read]')[Math.min(at,host.querySelectorAll('[data-brief-read]').length-1)];if(next)next.focus();else{host.tabIndex=-1;host.focus()}});
 expand?.addEventListener('click',e=>{list?.classList.toggle('expanded');e.currentTarget.textContent=list?.classList.contains('expanded')?'Mostrar menos':'Ver todo en Ponte al día'});
 host.querySelector('[data-feed-cue]')?.addEventListener('click',()=>document.getElementById('local')?.scrollIntoView({behavior:'smooth',block:'start'}));
}
function updateMetrics(v){const featured=activeType==='Todos'&&activeScope==='Todos'?specials().filter(specialInPeriod):[],selected=v.length+featured.length,unread=v.filter(s=>!isRead(s)).length+featured.filter(x=>!specialRead(x)).length;document.getElementById('radarMetrics').textContent=`${selected} tarjetas visibles tras filtros · ${unread} tarjetas no leídas`;document.getElementById('radarMetrics').title='El total bruto de señales detectadas no está disponible de forma auditable en esta vista.'}
let revealedHash='';
function sharedHashTarget(){try{return decodeURIComponent(location.hash.slice(1))}catch{return ''}}
function revealSharedHash(){const target=sharedHashTarget();if(!target)return;let element=document.getElementById(target);if(!element){const prefix=target.startsWith('special-')?'special-':target.startsWith('sig-')?'sig-':'',id=target.slice(prefix.length),signal=prefix==='sig-'?allSignals.find(x=>idFor(x)===id):null,special=prefix==='special-'?specials().find(x=>x.id===id):null;if(signal||special){activeType='Todos';activeScope='Todos';if(signal&&!inPeriod(signal)||special&&!specialInPeriod(special))periodMode='90';persistFilters();renderFilters();element=null}}if(!element)element=document.getElementById(target);if(element){revealedHash=target;requestAnimationFrame(()=>requestAnimationFrame(()=>{const current=document.getElementById(target);if(!current)return;current.focus({preventScroll:true});current.scrollIntoView({block:'start'})}))}}
async function shareCard(button){const url=new URL(location.href);url.hash=button.dataset.share;const payload={title:button.dataset.shareTitle,text:button.dataset.shareTitle,url:url.href},feedback=button.nextElementSibling,report=(state,message)=>{button.dataset.shareResult=state;button.title=message;button.setAttribute('aria-label',`${message}: ${button.dataset.shareTitle}`);if(feedback?.classList.contains('share-feedback'))feedback.textContent=message};try{if(navigator.share){await navigator.share(payload);report('shared','Compartido');return}if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(url.href);else{const field=document.createElement('textarea');field.value=url.href;field.setAttribute('readonly','');field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();const copied=document.execCommand('copy');field.remove();if(!copied)throw new Error('copy failed')}report('copied','Enlace copiado')}catch(error){if(error?.name!=='AbortError')report('error','No se pudo compartir')}}
function draw(){let v=visible(),xs=activeType==='Todos'&&activeScope==='Todos'?specials().filter(specialInPeriod):[];const hashTarget=sharedHashTarget();if(hashTarget&&!document.getElementById(hashTarget)){const id=hashTarget.replace(/^(sig-|special-)/,''),signal=hashTarget.startsWith('sig-')?allSignals.find(x=>idFor(x)===id):null,special=hashTarget.startsWith('special-')?specials().find(x=>x.id===id):null;if(signal||special){activeType='Todos';activeScope='Todos';if(signal&&!inPeriod(signal)||special&&!specialInPeriod(special))periodMode='90';const period=document.getElementById('period');if(period)period.value=periodMode;persistFilters();renderFilters();v=visible();xs=specials().filter(specialInPeriod)}}updateMetrics(v);brief();const combined=[...v.map(s=>({signal:s,date:dateVal(s),read:isRead(s)})),...xs.map(x=>({special:x,date:new Date(x.date).getTime(),read:specialRead(x)}))];combined.sort((a,b)=>Number(a.read)-Number(b.read)||(sortMode==='personalized'&&a.signal&&b.signal?personalizedScore(b.signal)-personalizedScore(a.signal):0)||b.date-a.date);document.getElementById('local').innerHTML=combined.map(x=>x.signal?card(x.signal):specialCard(x.special)).join('');document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{const signal=v.find(x=>idFor(x)===b.dataset.read);if(signal)setReadWithoutReorder(signal,!isRead(signal))});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const signal=v.find(x=>idFor(x)===b.dataset.detail);if(signal)openDetail(signal)});document.querySelectorAll('[data-special-read]').forEach(b=>b.onclick=()=>{const x=xs.find(s=>s.id===b.dataset.specialRead);if(x)setSpecialRead(x,!specialRead(x))});document.querySelectorAll('[data-special-open]').forEach(b=>b.onclick=()=>{const x=xs.find(s=>s.id===b.dataset.specialOpen);if(x)openSpecial(x)});document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>shareCard(b));document.querySelectorAll('[data-back-brief]').forEach(b=>b.onclick=()=>{const host=document.querySelector('main');host.tabIndex=-1;host.focus({preventScroll:true});host.scrollIntoView({behavior:'smooth',block:'start'})});revealSharedHash()}
function chips(id,values,current,setter){document.getElementById(id).innerHTML=values.map(v=>`<button class="chip ${v===current?'active':''}" data-v="${esc(v)}">${esc(v)}</button>`).join('');document.querySelectorAll(`#${id} .chip`).forEach(b=>b.onclick=()=>{setter(b.dataset.v);persistFilters();renderFilters();draw()})}
function renderFilters(){const types=['Todos',...['Normativa','Legal','Noticias','Datos','Fiscalización'].filter(x=>allSignals.some(s=>typeTags(s).includes(x)))];const scopes=['Todos',...new Set(allSignals.flatMap(scopeTags))];chips('typeFilters',types,activeType,v=>activeType=v);chips('scopeFilters',scopes,activeScope,v=>activeScope=v)}
function renderFreeValue(d){freeValue=d||{};const weekly=d.weekly_insight;document.getElementById('valueHighlights').hidden=true;if(weekly)document.getElementById('weeklyInsightBody').innerHTML=`<h2 id="weeklyInsightTitle">${esc(weekly.insight_title||weekly.title)}</h2><p class="meta-line">Insight trazado a ${esc(weekly.title)} · ${esc(weekly.source_name)} · ${fmtDate(weekly.event_date)}</p><p><strong>Qué cambió:</strong> ${esc(weekly.summary)}</p><p class="insight-reading"><strong>Lectura Alicanto:</strong> ${esc(weekly.insight_reading||weekly.why_it_matters)}</p><p><a href="${esc(weekly.source_url)}" target="_blank" rel="noopener">Revisar fuente original ↗</a></p>`;if(allSignals.length)draw()}
if(typeof fetch==='function')fetch('data/free_value.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('free value');return r.json()}).then(renderFreeValue).catch(()=>{});
fetch('data/radar_today.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('snapshot');return r.json()}).then(d=>{document.getElementById('meta').textContent=fmtUpdated(d.generated_at);allSignals=d.signals||[];migrateReads();const types=['Todos',...['Normativa','Legal','Noticias','Datos','Fiscalización'].filter(x=>allSignals.some(s=>typeTags(s).includes(x)))],scopes=['Todos',...new Set(allSignals.flatMap(scopeTags))];if(!types.includes(activeType))activeType='Todos';if(!scopes.includes(activeScope))activeScope='Todos';if(!['last','7','14','30','60','90'].includes(periodMode))periodMode='14';if(!['personalized','date'].includes(sortMode))sortMode='date';document.getElementById('sort').value=sortMode;const period=document.getElementById('period');period.value=periodMode;renderFilters();draw();persistFilters();period.onchange=e=>{periodMode=e.target.value;persistFilters();draw()};document.getElementById('sort').onchange=e=>{sortMode=e.target.value;persistFilters();draw()};saveLocal('alicanto_last_visit',new Date().toISOString())}).catch(()=>document.getElementById('local').innerHTML='<div>No se pudo cargar Alicanto.</div>');

function openDialog(id){const dialog=document.getElementById(id);if(dialog&&!dialog.open)dialog.showModal()}
document.getElementById('earlyAccessOpen').onclick=()=>openDialog('earlyAccessDialog');
document.getElementById('newsletterOpen').onclick=()=>openDialog('newsletterDialog');
document.getElementById('sourcesOpen').onclick=()=>openDialog('sourcesDialog');
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>document.getElementById(button.dataset.close).close());
document.querySelectorAll('.home-dialog').forEach(dialog=>dialog.onclick=event=>{if(event.target===dialog)dialog.close()});
fetch('data/product.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('sources');return r.json()}).then(d=>{const rows=Object.values(d.sources||{}).filter(x=>x&&x.name).sort((a,b)=>String(a.name).localeCompare(String(b.name),'es')),host=document.getElementById('sourcesList'),more=document.getElementById('sourcesMore');let expanded=false;const render=()=>{const visibleRows=expanded?rows:rows.slice(0,10);host.innerHTML=visibleRows.map(x=>`<div class="source-row"><strong>${esc(x.name)}</strong><span>${x.technical_status==='error'?'Temporalmente no disponible':x.last_signal_at?`Última señal ${fmtDate(x.last_signal_at)}`:'Monitoreo disponible · sin señal reciente'}</span></div>`).join('')||'<p>No hay fuentes registradas.</p>';more.hidden=rows.length<=10;more.textContent=expanded?'Ver menos':'Ver más'};more.onclick=()=>{expanded=!expanded;render();more.focus()};render()}).catch(()=>{document.getElementById('sourcesList').innerHTML='<p>No se pudo cargar la lista de fuentes.</p>'});

document.getElementById('closeDetail').onclick=()=>document.getElementById('signalDetail').close();
document.getElementById('signalDetail').onclick=e=>{if(e.target.id==='signalDetail')e.target.close()};
