const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dateText=raw=>new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Santiago'}).format(new Date(`${raw}T12:00:00Z`));
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function saveRead(){try{localStorage.setItem('alicanto_global_read',JSON.stringify([...readSet]))}catch{}}
const savedRead=stored('alicanto_global_read',[]),readSet=new Set(Array.isArray(savedRead)?savedRead:[]);
let themes=[];
function source(s){return `<div class="source"><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.publisher)} · ${esc(s.title)} ↗</a><span>Publicado ${dateText(s.published_at)} · capturado ${dateText(s.captured_at)} · ${esc(s.material_type)}</span><span>${esc(s.evidence)}</span></div>`}
function theme(t){const w=t.chile_watch||{},local=Array.isArray(w.compatible_local_signals)?w.compatible_local_signals:[],labels={not_established:'no establecido',candidate:'candidato',established:'establecido'},read=readSet.has(t.id);return `<article class="theme ${read?'read':''}" id="theme-${esc(t.id)}"><div class="theme-head"><div><div class="eyebrow">Global Theme · research internacional</div><h2>${esc(t.title)}</h2></div><button type="button" class="read-toggle" data-read="${esc(t.id)}">${read?'Marcar no leído':'Marcar como leído'}</button></div><p class="theme-summary"><strong>Por qué importa:</strong> ${esc(t.why_it_matters)}</p><details><summary>Ver análisis completo</summary><p><strong>Qué encontró:</strong> ${esc(t.global_finding)}</p><div class="watch"><strong>Qué mirar en Chile · hipótesis, no evidencia local</strong><p>${esc(w.text)}</p><div class="status">Trend Chile: ${labels[w.trend_chile_status]||'estado inválido'} · señales locales compatibles verificadas: ${local.length}</div></div><div class="sources"><strong>Fuentes del tema</strong>${(t.sources||[]).map(source).join('')}</div><button type="button" class="back-inbox" data-back hidden>Volver a Global Intelligence</button></details></article>`}
function renderInbox(){const unread=themes.filter(t=>!readSet.has(t.id)),host=document.getElementById('globalInbox');host.innerHTML=`<h2 id="globalInboxTitle">Tu bandeja Global Intelligence</h2><p class="inbox-meta"><strong>${unread.length}</strong> temas no leídos · selección internacional para profundizar</p><div>${unread.length?unread.map(t=>`<div class="inbox-row"><button type="button" class="inbox-open" data-open="${esc(t.id)}">${esc(t.title)}</button><button type="button" class="inbox-read" data-inbox-read="${esc(t.id)}" aria-label="Marcar como leído: ${esc(t.title)}">Leído ✓</button></div>`).join(''):'<p>Estás al día con los temas globales disponibles.</p>'}</div>`;host.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openTheme(b.dataset.open));host.querySelectorAll('[data-inbox-read]').forEach((b,index)=>b.onclick=()=>setRead(b.dataset.inboxRead,true,'inbox',index))}
function wireThemes(){document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>setRead(b.dataset.read,!readSet.has(b.dataset.read),'theme'));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{const inbox=document.getElementById('globalInbox');inbox.tabIndex=-1;inbox.focus({preventScroll:true});inbox.scrollIntoView({behavior:'smooth',block:'start'})})}
function renderThemes(){document.getElementById('themes').innerHTML=themes.map(theme).join('')||'<p class="empty">No hay research material aprobado.</p>';wireThemes()}
function render(){renderInbox();renderThemes()}
function syncThemeState(id){const article=document.getElementById(`theme-${id}`);if(!article)return;const read=readSet.has(id);article.classList.toggle('read',read);article.querySelector('[data-read]').textContent=read?'Marcar no leído':'Marcar como leído'}
function setRead(id,value,origin='theme',index=0){if(value)readSet.add(id);else readSet.delete(id);saveRead();syncThemeState(id);renderInbox();if(origin==='inbox'){const next=document.querySelectorAll('[data-inbox-read]')[Math.min(index,document.querySelectorAll('[data-inbox-read]').length-1)];if(next)next.focus();else{const inbox=document.getElementById('globalInbox');inbox.tabIndex=-1;inbox.focus()}}}
function openTheme(id){readSet.add(id);saveRead();syncThemeState(id);renderInbox();const article=document.getElementById(`theme-${id}`);if(!article)return;article.querySelector('details').open=true;article.querySelector('[data-back]').hidden=false;article.tabIndex=-1;article.focus({preventScroll:true});article.scrollIntoView({behavior:'smooth',block:'start'})}
fetch('data/global_themes.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('global themes');return r.json()}).then(d=>{document.getElementById('updated').textContent=`Actualizado ${dateText(String(d.generated_at).slice(0,10))}`;themes=d.themes||[];render()}).catch(()=>{document.getElementById('globalInbox').innerHTML='<p>No se pudo cargar la bandeja Global Intelligence.</p>';document.getElementById('themes').innerHTML='<p class="empty">No se pudo cargar Global Intelligence.</p>'});
